// packages/docs/src/lib/components/BadgePreview.svelte
<script lang="ts">
	import { Badge } from "feflow-svelte"

	const variants = ["outlined", "text", "contained"]
	const colors = ["error", "success", "warning", "info", "primary"]
	const sizes = ["xs", "sm", "md", "lg", "xl"]
</script>

<div
	style="
    display: flex; 
    flex-wrap: wrap;
    align-items: flex-end;
    gap: 1rem;
    "
>
	{#each colors as color}
		<Badge class="bg-{color} text-on-{color}" size="md">
			{color}
		</Badge>
	{/each}
	{#each variants as variant}
		<Badge variant={variant as any} size="md">
			{variant}
		</Badge>
	{/each}
	{#each sizes as size}
		<Badge roundedFull size={size as any}>
			{size}
		</Badge>
	{/each}
</div>

// packages/docs/src/lib/components/BadgePreview.tsx
import { Badge } from "@feflow-ui/react"

export default function () {
	const variants = ["outlined", "contained"] as const
	const colors = ["error", "success", "warning", "info", "primary"] as const
	const sizes = ["xs", "sm", "md", "lg", "xl"] as const

	return (
		<div
			style={{
				display: "flex",
				flexWrap: "wrap",
				alignItems: "flex-end",
				gap: "1rem"
			}}
		>
			{colors.map((color) => (
				<Badge
					key={`color-${color}`}
					className={`bg-${color} text-on-${color}`}
					size="md"
				>
					{color}
				</Badge>
			))}

			{variants.map((variant) => (
				<Badge key={`variant-${variant}`} variant={variant} size="md">
					{variant}
				</Badge>
			))}

			{sizes.map((size) => (
				<Badge key={`size-${size}`} size={size} roundedFull>
					{size}
				</Badge>
			))}
		</div>
	)
}
