// packages/docs/src/lib/components/BottomSheetPreview.tsx
import { BottomSheet, Button } from "@dxdns-kit/react"
import { useEffect, useState } from "react"

export default function () {
	const [isOpen, setIsOpen] = useState(false)
	const [variant, setVariant] = useState("")

	function handleOpen(s: string) {
		setVariant(s)
		setIsOpen((old) => !old)
	}

	function handleClose() {
		setIsOpen(false)
	}

	useEffect(() => {
		handleOpen("text")
	}, [])

	return (
		<>
			<BottomSheet.Overlay
				isOpen={isOpen}
				onClick={handleClose}
				style={{ zIndex: 998 }}
			/>
			<BottomSheet isOpen={isOpen} handleClose={handleClose}>
				<BottomSheet.DragButton variant={variant as any} />
				<BottomSheet.Content>
					<h1>test</h1>
				</BottomSheet.Content>
			</BottomSheet>

			<div style={{ display: "flex", gap: "1rem", flexWrap: "wrap" }}>
				{["text", "contained", "outlined"].map((variant, i) => (
					<Button
						key={`${variant}-${i}`}
						onClick={() => {
							handleOpen(variant)
						}}
					>
						{variant}
					</Button>
				))}
			</div>
		</>
	)
}

// packages/docs/src/lib/components/BottomSheetPreview.svelte
<script lang="ts">
	import { BottomSheet, Button } from "@dxdns-kit/svelte"
	import { onMount } from "svelte"

	let isOpen = $state(false)
	let variant = $state("")

	function handleOpen(s: string) {
		variant = s
		isOpen = !isOpen
	}

	function handleClose() {
		isOpen = false
	}

	onMount(() => {
		handleOpen("text")
	})
</script>

<BottomSheet.Overlay {isOpen} onclick={handleClose} style="z-index: 998;" />
<BottomSheet {isOpen} {handleClose}>
	<BottomSheet.DragButton variant={variant as any} />
	<BottomSheet.Content>
		<h1>test</h1>
	</BottomSheet.Content>
</BottomSheet>

<div style="display: flex; gap: 1rem; flex-wrap: wrap;">
	{#each ["text", "contained", "outlined"] as variant (variant)}
		<Button
			onclick={() => {
				handleOpen(variant)
			}}
		>
			{variant}
		</Button>
	{/each}
</div>
