// packages/docs/src/lib/components/CheckboxPreview.tsx
import { Constants } from "@fefade/core"
import { Checkbox } from "@fefade/react"

export default function () {
	const colors = [...Constants.statusColors, "secondary"] as const

	return (
		<>
			<Checkbox label="checked" checked />
			<Checkbox label="disabled" disabled />
			<br />
			{colors.map((color) => (
				<Checkbox key={color} label={color} color={color} />
			))}
		</>
	)
}

// packages/docs/src/lib/components/CheckboxPreview.svelte
<script lang="ts">
	import { Checkbox } from "@fefade/svelte"
	import { Constants } from "@fefade/core"

	const colors = [...Constants.statusColors, "secondary"] as const
</script>

<Checkbox label="checked" checked />
<Checkbox label="disabled" disabled />
<br />
{#each colors as color (color)}
	<Checkbox label={color} {color} />
{/each}
