// packages/docs/src/lib/components/ModalPreview.svelte
<script lang="ts">
	import { Button, Modal } from "@dxdns-kit/svelte"

	let isOpen = $state(false)

	function handleClose() {
		isOpen = false
	}
</script>

<Modal {isOpen} {handleClose}>
	<Modal.Header {handleClose} align="center">
		<h2>test header</h2>
	</Modal.Header>
	<Modal.Content>
		<p>test content</p>
	</Modal.Content>
	<Modal.Actions class="border-0" align="center" style="align-items: baseline;">
		<Button variant="outlined" onclick={handleClose}>Cancel</Button>
		<Button>Save</Button>
	</Modal.Actions>
</Modal>

<Button
	onclick={() => {
		isOpen = !isOpen
	}}
>
	Open Modal
</Button>

// packages/docs/src/lib/components/ModalPreview.tsx
import { Button, Modal } from "@dxdns-kit/react"
import { useEffect, useState } from "react"

export default function () {
	const [isOpen, setIsOpen] = useState(false)

	function handleClose() {
		setIsOpen(false)
	}

	useEffect(() => {
		setIsOpen(true)
	}, [])

	return (
		<>
			<Modal isOpen={isOpen} handleClose={handleClose}>
				<Modal.Header handleClose={handleClose} align="center">
					<h2>test header</h2>
				</Modal.Header>
				<Modal.Content>
					<p>test content</p>
				</Modal.Content>
				<Modal.Actions className="border-0" align="center">
					<Button variant="outlined" onClick={handleClose}>
						Cancel
					</Button>
					<Button>Save</Button>
				</Modal.Actions>
			</Modal>
			<Button
				onClick={() => {
					setIsOpen(true)
				}}
			>
				Open modal
			</Button>
		</>
	)
}
