// packages/docs/src/lib/components/svelte/NumberInputPreview.svelte
<script lang="ts">
	import { NumberInput } from "@dxdns/feflow-svelte"

	let quantity = $state(0)
</script>

<div style="max-width: 150px; margin: 0 auto;">
	{#each ["text", "contained", "outlined"] as variant}
		<NumberInput
			autoFocus
			variant={variant as any}
			bind:value={quantity}
			min={0}
			max={10}
		/>
	{/each}
	<NumberInput disabled bind:value={quantity} />
</div>

// packages/docs/src/lib/components/NumberInputPreview.tsx
import { useState } from "react"
import { Constants } from "@dxdns-kit/core"
import { NumberInput } from "@dxdns-kit/react"

export default function () {
	const [quantity, setQuantity] = useState(0)

	return (
		<div style={{ maxWidth: "150px", margin: "0 auto" }}>
			{Constants.variants.map((variant, i) => (
				<NumberInput
					key={variant}
					id={`${variant}-${i}`}
					variant={variant}
					value={quantity}
					onChange={(val: number) => setQuantity(val)}
					min={0}
					max={10}
				/>
			))}
		</div>
	)
}
