// packages/docs/src/lib/components/SearchInputPreview.svelte
<script lang="ts">
	import { Constants } from "@dxdns-kit/core"
	import { SearchInput } from "@dxdns-kit/svelte"
</script>

<div
	style="display: flex; flex-direction: column; gap: 1rem; max-width: 300px; margin: 1rem auto;"
>
	{#each Constants.variants as variant (variant)}
		<SearchInput placeholder={variant} {variant} />
	{/each}
</div>

// packages/docs/src/lib/components/SearchInputPreview.tsx
import { Constants } from "@dxdns-kit/core"
import { SearchInput } from "@dxdns-kit/react"

export default function () {
	return (
		<div
			style={{
				display: "flex",
				flexDirection: "column",
				gap: "1rem",
				maxWidth: "300px",
				margin: "1rem auto"
			}}
		>
			{Constants.variants.map((variant) => (
				<SearchInput key={variant} placeholder={variant} variant={variant} />
			))}
		</div>
	)
}
