// packages/docs/src/lib/components/StatusPreview.tsx
import { Status } from "@dxdns/feflow-react"

export default function () {
	const variants = ["pulse", "ping", "bounce"]

	return (
		<div style={{ maxWidth: "300px", margin: "0 auto", lineHeight: 3 }}>
			{variants.map((variant, i) => (
				<div key={variant}>
					<Status
						variant={variant as any}
						color={i % 2 ? "var(--ff-success)" : "var(--ff-error)"}
					/>
					<br />
				</div>
			))}

			{["5rem", 100, "150px", 200].map((size, i) => (
				<div key={size}>
					<Status
						color={i % 2 ? "var(--ff-info)" : "var(--ff-warning)"}
						variant={i % 2 ? "bounce" : "none"}
						size={size}
					/>
					<br />
				</div>
			))}
		</div>
	)
}

// packages/docs/src/lib/components/StatusPreview.svelte
<script lang="ts">
	import { Status, themeConfig } from "@dxdns/feflow-svelte"

	const { colors } = $derived(themeConfig())
	const variants = ["pulse", "ping", "bounce"]
</script>

<div style="max-width: 300px; margin: 0 auto; line-height: 3;">
	{#each variants as variant, i}
		<Status
			variant={variant as any}
			color={i % 2 ? colors.success : colors.error}
		/>
		<br />
	{/each}

	{#each ["5rem", 100, "150px", 200] as size, i}
		<Status
			color={i % 2 ? colors.info : colors.warning}
			variant={i % 2 ? "bounce" : "none"}
			{size}
		/>
		<br />
	{/each}
</div>
