// packages/docs/src/lib/components/TextFieldPreview.tsx
import { TextField } from "@dxdns/feflow-react"

export default function () {
	const sizes = ["xs", "sm", "md", "lg", "xl"]
	const variants = ["contained", "text", "outlined"]

	return (
		<div
			style={{
				maxWidth: "300px",
				margin: "0 auto"
			}}
		>
			{variants.map((variant, i) => {
				const size = sizes[i + 1] as any
				return (
					<div key={i}>
						<TextField
							label={`${variant} (${size})`}
							variant={variant as any}
							size={size}
						/>
						<br />
						<br />
					</div>
				)
			})}
		</div>
	)
}

// packages/docs/src/lib/components/TextFieldPreview.svelte
<script lang="ts">
	import { TextField } from "@dxdns/feflow-svelte"

	const sizes = ["xs", "sm", "md", "lg", "xl"]
	const variants = ["contained", "text", "outlined"]
</script>

<div style="max-width: 300px; margin: 0 auto;">
	{#each variants as variant, i (i)}
		{@const size = sizes[i + 1] as any}
		<TextField label={`${variant} (${size})`} variant={variant as any} {size} />
		<br />
		<br />
	{/each}
</div>
