// packages/docs/src/lib/components/ThemeColorPreview.tsx
import { Badge, Button, Card, FeflowProvider, themeConfig } from "@dxdns/feflow-react"

function ThemeColorPreview() {
	const theme = themeConfig()

	return (
		<>
			<div
				style={{
					display: "flex",
					flexWrap: "wrap",
					gap: "1rem",
					alignItems: "center",
				}}
			>
				<h2>{theme.mode}</h2>
				<Button variant="outlined" onClick={theme.toggle}>toggle theme</Button>
			</div>
			<Card style={{ background: theme.mode === 'dark' ? 'green' : 'red' }}>
				<ul style={{ lineHeight: 2 }}>
					{Object.keys(theme.colors).map((t) => {
						const color = theme.colors[t as keyof typeof theme.colors]
						return (
							<li>
								<span style={{ color: "aqua" }}>{t}</span>:
								<Badge roundedFull style={{ background: color }} size="sm"></Badge>
							</li>
						)
					})}
				</ul>
			</Card>
		</>
	)
}

export default function () {
	return (
		<FeflowProvider>
			<ThemeColorPreview />
		</FeflowProvider>
	)
}

// packages/docs/src/lib/components/ThemeColorPreview.svelte
<script lang="ts">
	import { Badge, Button, Card, themeConfig } from "@dxdns/feflow-svelte"

	const theme = $derived(themeConfig())
</script>

<div
	style="
    display: flex; 
    flex-wrap: wrap; 
    gap: 1rem; 
    align-items: center;
    "
>
	<h2>{theme.mode}</h2>
	<Button variant="outlined" onclick={theme.toggle}>toggle theme</Button>
</div>
<Card style="background: {theme.mode === 'dark' ? 'green' : 'red'};">
	<ul style="line-height: 2;">
		{#each Object.keys(theme.colors) as t (t)}
			{@const color = theme.colors[t as keyof typeof theme.colors]}
			<li>
				<span style="color:aqua;">{t}</span>:
				<Badge roundedFull style="background: {color};" size="sm"></Badge>
			</li>
		{/each}
	</ul>
</Card>
