// packages/docs/src/lib/components/TooltipPreview.svelte
<script lang="ts">
	import { Tooltip } from "@dxdns-kit/svelte"

	const positions = ["top", "bottom", "left", "right"] as const
</script>

<div
	style="
	max-width: 300px; 
	margin: 5rem auto; 
	display: flex; 
	flex-direction: column;
	gap: 1rem;
	"
>
	{#each positions as position (position)}
		<Tooltip label={position} {position}>
			<p>{position}</p>
		</Tooltip>
	{/each}
</div>

// packages/docs/src/lib/components/TooltipPreview.tsx
import { Tooltip } from "@dxdns-kit/react"

export default function () {
	const positions = ["top", "bottom", "left", "right"] as const

	return (
		<div
			style={{
				maxWidth: "300px",
				margin: "5rem auto",
				display: "flex",
				flexDirection: "column",
				gap: "1rem"
			}}
		>
			{positions.map((position) => (
				<Tooltip key={position} label={position} position={position}>
					<p>{position}</p>
				</Tooltip>
			))}
		</div>
	)
}
