// packages/docs/src/lib/components/svelte/UseMediaQueryPreview.svelte
<script lang="ts">
	import { useMediaQuery } from "@feflow/svelte"
	import { onDestroy } from "svelte"

	const isSm = $derived(useMediaQuery("max-width", "sm"))
	const isMd = $derived(useMediaQuery("max-width", "md"))
	const isCustom = $derived(useMediaQuery("max-width", "800px"))

	onDestroy(() => {
		isSm.destroy()
		isMd.destroy()
		isCustom.destroy()
	})
</script>

<h4>isSm: {isSm.value}</h4>
<h4>isMd: {isMd.value}</h4>
<h4>isCustom: {isCustom.value}</h4>

// packages/docs/src/lib/components/UseMediaQueryPreview.tsx
import { useMediaQuery } from "@fefade/react"

export default function () {
	const isSm = useMediaQuery("max-width", "sm")
	const isMd = useMediaQuery("max-width", "md")
	const isCustom = useMediaQuery("max-width", "800px")

	return (
		<>
			<h4>sm (425px): {String(isSm)}</h4>
			<h4>md (768px): {String(isMd)}</h4>
			<h4>custom (800px): {String(isCustom)}</h4>
		</>
	)
}
