// packages/docs/src/lib/components/VisibilityListenerPreview.tsx
import { useState } from "react"
import { VisibilityListener } from "@navnex-kit/react"

export default function () {
	const [isVisible, setIsVisible] = useState(false)
	const n = 50

	return (
		<div>
			<h2>
				{n} is visible:{" "}
				<span style={{ color: "aqua" }}>{isVisible ? "Yes" : "No"}</span>
			</h2>
			<div
				style={{ height: "200px", overflowY: "auto", border: "1px solid #ccc" }}
			>
				{Array.from({ length: 100 }, (_, i) => (
					<div key={i}>
						{i === n ? (
							<VisibilityListener
								callback={(isVisible) => {
									setIsVisible(isVisible)
								}}
							>
								<p style={{ color: "aqua" }}>{i} visible</p>
							</VisibilityListener>
						) : (
							<p>{i}</p>
						)}
					</div>
				))}
			</div>
		</div>
	)
}

// packages/docs/src/lib/components/VisibilityListenerPreview.svelte
<script lang="ts">
	import { VisibilityListener } from "@navnex-kit/svelte"

	let isVisible = $state(false)
	const n = 50
</script>

<h2>{n} is visibile: <span style="color: aqua;">{isVisible}</span></h2>
<div style="height: 200px; overflow-y: auto; border: 1px solid #ccc;">
	{#each Array(100) as _, i (i)}
		{#if i === n}
			<VisibilityListener
				callback={(value) => {
					isVisible = value
				}}
			>
				<p style="color: aqua;">{i} visible</p>
			</VisibilityListener>
		{:else}
			<p>{i}</p>
		{/if}
	{/each}
</div>
