// packages/docs/src/lib/components/WindowPreview.svelte
<script lang="ts">
	import { Window } from "@dxdns-kit/svelte"

	const windowVariants = ["contained", "outlined"] as const
</script>

<div style="display: flex; flex-direction: column; gap: 1rem;">
	{#each windowVariants as variant (variant)}
		<Window {variant}>
			<h2>{variant}</h2>
		</Window>
	{/each}

	<Window animatedBorder>
		<h2>animated border</h2>
	</Window>
</div>

// packages/docs/src/lib/components/WindowPreview.tsx
import { Window } from "@dxdns-kit/react"

export default function () {
	const windowVariants = ["contained", "outlined"] as const

	return (
		<div style={{ display: "flex", flexDirection: "column", gap: "1rem" }}>
			{windowVariants.map((variant) => (
				<Window key={variant} variant={variant}>
					<h2>{variant}</h2>
				</Window>
			))}
			<Window animatedBorder>
				<h2>animated border</h2>
			</Window>
		</div>
	)
}
