// packages/react/src/lib/components/window/Window.tsx
import { forwardRef, HTMLAttributes, ReactNode } from "react"
import { VariantType } from "@dxdns/feflow-core/types"
import Card from "../card"
import Badge from "../badge"
import styles from "@dxdns/feflow-core/styles/Window.module.css"

interface Props extends Omit<HTMLAttributes<HTMLDivElement>, "color"> {
	label?: string | ReactNode
	variant?: Exclude<VariantType, "text">
}

export default forwardRef<HTMLDivElement, Props>(
	({ className, label, children, ...rest }, ref) => {
		return (
			<Card {...rest} ref={ref} className={className}>
				<div className={styles.header}>
					<div className={styles.actions}>
						<Badge className="bg-error" roundedFull size="xs"></Badge>
						<Badge className="bg-warning" roundedFull size="xs"></Badge>
						<Badge className="bg-success" roundedFull size="xs"></Badge>
					</div>
					{label}
				</div>
				{children}
			</Card>
		)
	}
)

// packages/feflow/src/lib/components/window/Window.svelte
<script lang="ts">
	import type { HTMLAttributes } from "svelte/elements"
	import Card from "../card/index.js"
	import Badge from "../badge/index.js"
	import type { Snippet } from "svelte"
	import type { VariantType } from "../../types/variant.types.js"

	interface Props extends HTMLAttributes<HTMLDivElement> {
		label?: string | Snippet<[]>
		variant?: Exclude<VariantType, "text">
	}

	let { class: className = "", label, children, ...rest }: Props = $props()
</script>

<Card {...rest} class={className}>
	<div class="header">
		<div class="actions">
			<Badge class="bg-error" roundedFull size="xs"></Badge>
			<Badge class="bg-warning" roundedFull size="xs"></Badge>
			<Badge class="bg-success" roundedFull size="xs"></Badge>
		</div>
		{#if typeof label === "string"}
			{label}
		{:else}
			{@render label?.()}
		{/if}
	</div>
	{@render children?.()}
</Card>

<style>
	.header {
		display: flex;
		align-items: center;
		gap: 1rem;
		margin-bottom: 15px;
		height: 30px;
		user-select: none;
	}

	.actions {
		display: flex;
		gap: 5px;
		align-items: center;
	}
</style>
