// src/lib/components/modal/Modal.svelte
<script lang="ts">
	import type { ClassValue, HTMLAttributes } from "svelte/elements"
	import styles from "./Modal.module.css"
	import classMapUtil from "../../utils/classMapUtil.js"
	import { fade, scale } from "svelte/transition"
	import IconButton from "../icon-button/index.js"
	import Card from "../card/index.js"
	import type { Snippet } from "svelte"

	interface Props extends HTMLAttributes<HTMLDivElement> {
		class?: ClassValue
		label: string | Snippet
		isOpen: boolean
		handleClose: {
			handler: () => void
			icon?: Snippet
		}
	}

	let {
		class: className = "",
		label,
		isOpen,
		handleClose,
		children,
		...rest
	}: Props = $props()

	function handleBgClick(e: MouseEvent) {
		if (e.target === e.currentTarget) {
			handleClose.handler()
		}
	}
</script>

{#if isOpen}
	<div class={styles.overlay}></div>
	<div
		{...rest}
		class={classMapUtil({
			[className as string]: true,
			[styles.modal]: true
		})}
	>
		<div
			class={styles.bg}
			in:fade={{ duration: 300 }}
			out:fade={{ duration: 300 }}
			role="button"
			tabindex="0"
			onkeydown={(e) =>
				e.key === "Enter" || e.key === " " ? handleClose.handler() : null}
			onclick={handleBgClick}
		>
			<div
				class={styles.wrapper}
				in:scale={{ duration: 300 }}
				out:scale={{ duration: 300 }}
			>
				<Card>
					<div class={styles.header}>
						{#if typeof label === "string"}
							<h2>{label}</h2>
						{:else}
							{@render label?.()}
						{/if}
						{#if handleClose.icon}
							<IconButton onclick={handleClose.handler}>
								{@render handleClose.icon?.()}
							</IconButton>
						{/if}
					</div>
					<div class={styles.content}>
						{@render children?.()}
					</div>
				</Card>
			</div>
		</div>
	</div>
{/if}

// packages/react/src/lib/components/modal/Modal.tsx
import type { ModalType } from "@feflow-ui/core/types"
import { classMapUtil } from "@feflow-ui/core/utils"
import { forwardRef, HTMLAttributes, useEffect, useRef, useState } from "react"
import { Card } from "../card"
import styles from "@feflow-ui/core/styles/Modal.module.css"
import animationStyle from "@feflow-ui/core/styles/Animation.module.css"

interface Props
	extends Omit<HTMLAttributes<HTMLDivElement>, "color">,
		ModalType {}

export default forwardRef<HTMLDivElement, Props>(
	(
		{
			className = "",
			isOpen,
			handleClose,
			variant = "contained",
			children,
			...rest
		},
		ref
	) => {
		const [show, setShow] = useState(false)

		const el = useRef<HTMLDivElement | null>(null)

		useEffect(() => {
			if (isOpen) {
				el.current?.focus()
				setShow(true)
			}
		}, [isOpen])

		if (!show) return null

		return (
			<div
				className={classMapUtil(className, [className, styles], styles.modal)}
			>
				<div
					ref={ref ?? el}
					className={classMapUtil(styles.overlay, {
						[animationStyle.fadeIn]: isOpen,
						[animationStyle.fadeOut]: !isOpen
					})}
					role="alertdialog"
					tabIndex={0}
					onKeyDown={(e) => {
						if (e.key === "Escape" || e.key === " ") {
							handleClose()
						}
					}}
					onClick={(e) => {
						if (e.target === e.currentTarget) {
							handleClose()
						}
					}}
					onAnimationEnd={() => {
						if (!isOpen) {
							setShow(false)
						}
					}}
				>
					<div
						className={classMapUtil(styles.wrapper, {
							[animationStyle.scaleIn]: isOpen,
							[animationStyle.scaleOut]: !isOpen
						})}
					>
						<Card {...rest} className={styles.content} variant={variant}>
							{children}
						</Card>
					</div>
				</div>
			</div>
		)
	}
)
