// packages/feflow/src/lib/components/modal/Modal.svelte
<script lang="ts">
	import type { HTMLAttributes } from "svelte/elements"
	import styles from "./Modal.module.css"
	import { classMapUtil } from "@dxdns/feflow-core/utils"
	import { fade, scale } from "svelte/transition"
	import Card from "../card/index.js"
	import type { VariantType } from "../../types/index.js"

	export interface ModalProps {
		isOpen: boolean
		handleClose: () => void
		variant?: Exclude<VariantType, "text">
	}

	interface Props extends ModalProps, HTMLAttributes<HTMLDivElement> {}

	let {
		class: className = "",
		isOpen,
		handleClose,
		variant = "contained",
		children,
		...rest
	}: Props = $props()

	let el: HTMLDivElement | undefined = $state()

	$effect(() => {
		if (isOpen) {
			el?.focus()
		}
	})
</script>

{#if isOpen}
	<div class={classMapUtil(className, [className, styles], styles.modal)}>
		<div
			bind:this={el}
			class={styles.overlay}
			in:fade={{ duration: 300 }}
			out:fade={{ duration: 300 }}
			role="alertdialog"
			tabindex="0"
			onkeydown={(e) => {
				e.key === "Escape" || e.key === " " ? handleClose() : null
			}}
			onclick={(e) => {
				if (e.target === e.currentTarget) {
					handleClose()
				}
			}}
		>
			<div
				class={styles.wrapper}
				in:scale={{ duration: 300 }}
				out:scale={{ duration: 300 }}
			>
				<Card {...rest} class={styles.content} {variant}>
					{@render children?.()}
				</Card>
			</div>
		</div>
	</div>
{/if}

// packages/react/src/lib/components/modal/Modal.tsx
import type { ModalType } from "@dxdns/feflow-core/types"
import { classMapUtil } from "@dxdns/feflow-core/utils"
import { forwardRef, HTMLAttributes, useEffect, useRef, useState } from "react"
import { Card } from "../card"
import styles from "@dxdns/feflow-core/styles/Modal.module.css"
import animationStyle from "@dxdns/feflow-core/styles/Animation.module.css"

interface Props
	extends Omit<HTMLAttributes<HTMLDivElement>, "color">,
		ModalType {}

export default forwardRef<HTMLDivElement, Props>(
	(
		{
			className = "",
			isOpen,
			handleClose,
			variant = "contained",
			children,
			...rest
		},
		ref
	) => {
		const [show, setShow] = useState(false)

		const el = useRef<HTMLDivElement | null>(null)

		useEffect(() => {
			if (isOpen) {
				el.current?.focus()
				setShow(true)
			}
		}, [isOpen])

		if (!show) return null

		return (
			<div
				className={classMapUtil(className, [className, styles], styles.modal)}
			>
				<div
					ref={ref ?? el}
					className={classMapUtil(styles.overlay, {
						[animationStyle.fadeIn]: isOpen,
						[animationStyle.fadeOut]: !isOpen
					})}
					role="alertdialog"
					tabIndex={0}
					onKeyDown={(e) => {
						if (e.key === "Escape" || e.key === " ") {
							handleClose()
						}
					}}
					onClick={(e) => {
						if (e.target === e.currentTarget) {
							handleClose()
						}
					}}
					onAnimationEnd={() => {
						if (!isOpen) {
							setShow(false)
						}
					}}
				>
					<div
						className={classMapUtil(styles.wrapper, {
							[animationStyle.scaleIn]: isOpen,
							[animationStyle.scaleOut]: !isOpen
						})}
					>
						<Card {...rest} className={styles.content} variant={variant}>
							{children}
						</Card>
					</div>
				</div>
			</div>
		)
	}
)
