// packages/feflow/src/lib/components/modal/ModalContent.svelte
<script lang="ts">
	import type { HTMLAttributes } from "svelte/elements"
	import { classMapUtil } from "@dxdns/feflow-core/utils"

	interface Props extends HTMLAttributes<HTMLDivElement> {}

	let { class: className = "", children, ...rest }: Props = $props()
</script>

<div {...rest} class={classMapUtil(className, "content")}>
	{@render children?.()}
</div>

<style>
	.content {
		padding: 0 0 0.5rem 3px;
		max-height: 80vh;
		overflow: auto;
		box-sizing: border-box;
	}
</style>

// packages/react/src/lib/components/modal/ModalContent.tsx
import { classMapUtil } from "@dxdns/feflow-core/utils"
import { forwardRef, HTMLAttributes } from "react"
import styles from "@dxdns/feflow-core/styles/ModalContent.module.css"

interface Props extends Omit<HTMLAttributes<HTMLDivElement>, "color"> {}

export default forwardRef<HTMLDivElement, Props>(
	({ className = "", children, ...rest }, ref) => {
		return (
			<div
				{...rest}
				ref={ref}
				className={classMapUtil(className, [className, styles], styles.content)}
			>
				{children}
			</div>
		)
	}
)
