// packages/svelte/src/lib/components/link/Link.svelte
<script lang="ts">
	import type { HTMLAnchorAttributes } from "svelte/elements"
	import { classMapUtil } from "@fefade/core/utils"
	import type { LinkType, VariantType } from "@fefade/core/types"
	import styles from "@fefade/core/styles/Link.module.css"
	import buttonStyles from "@fefade/core/styles/Button.module.css"

	interface Props extends Omit<HTMLAnchorAttributes, "class">, LinkType {
		variant?: VariantType
	}

	let {
		class: className = "",
		pathname,
		hover,
		variant = "text",
		children,
		...rest
	}: Props = $props()

	const isActive = $derived(
		rest.href && pathname
			? pathname === rest.href
			: rest["aria-current"] === "page"
	)
</script>

<a
	{...rest}
	class={classMapUtil(
		typeof className === "function" ? className({ isActive }) : className,
		[variant, buttonStyles],
		buttonStyles.button,
		styles.link,
		{
			[styles.hasHover]: Boolean(hover),
			[styles[hover!]]: Boolean(hover)
		}
	)}
	aria-current={isActive ? "page" : undefined}
>
	{@render children?.()}
</a>

// packages/react/src/lib/components/link/Link.tsx
import type { LinkType, VariantType } from "@fefade/core/types"
import { classMapUtil } from "@fefade/core/utils"
import {
	ComponentPropsWithoutRef,
	ElementType,
	forwardRef,
	JSX,
	PropsWithChildren,
	Ref
} from "react"
import styles from "@fefade/core/styles/Link.module.css"
import buttonStyles from "@fefade/core/styles/Button.module.css"

type AsProp<C extends ElementType> = {
	as?: C
	variant?: VariantType
}

type PropsToOmit<C extends ElementType, P> = keyof (AsProp<C> & P)

type PolymorphicComponentProps<
	C extends ElementType,
	Props = {}
> = PropsWithChildren<Props & AsProp<C>> &
	Omit<ComponentPropsWithoutRef<C>, PropsToOmit<C, Props>>

type Props<C extends ElementType> = PolymorphicComponentProps<C, LinkType>

function LinkComponent<C extends ElementType = "a">(
	{
		className = "",
		pathname,
		hover,
		variant = "text",
		as,
		children,
		...rest
	}: Props<C>,
	ref: Ref<any>
) {
	const Component = as || "a"

	const target = (rest as any).href || (rest as any).to
	const isActive =
		target && pathname
			? pathname === target
			: (rest as Record<string, any>)["aria-current"] === "page"

	return (
		<Component
			{...rest}
			ref={ref}
			className={classMapUtil(
				typeof className === "function" ? className({ isActive }) : className,
				[variant, buttonStyles],
				buttonStyles.button,
				styles.link,
				{
					[styles.hasHover]: Boolean(hover),
					[styles[hover!]]: Boolean(hover)
				}
			)}
			aria-current={isActive ? "page" : undefined}
		>
			{children}
		</Component>
	)
}

const Link = forwardRef(LinkComponent) as <C extends ElementType = "a">(
	props: Props<C> & { ref?: Ref<any> }
) => JSX.Element

export default Link
