// packages/react/src/lib/components/accordion/Accordion.tsx
import { forwardRef, HTMLAttributes } from "react"
import type { AccordionType } from "@dxdns/feflow-core/types"
import { classMapUtil } from "@dxdns/feflow-core/utils"
import styles from "@dxdns/feflow-core/styles/Accordion.module.css"
import { KeyboardArrowLeftIcon } from "../../icons"

interface Props
	extends Omit<HTMLAttributes<HTMLDivElement>, "id">,
		AccordionType {}

export default forwardRef<HTMLDivElement, Props>(
	({ className, label, variant, children, ...rest }, ref) => {
		return (
			<div
				ref={ref}
				className={classMapUtil(
					className,
					[className, styles],
					[variant, styles],
					styles.accordion
				)}
				style={rest.style}
			>
				<input
					{...rest}
					className={styles.controller}
					type="radio"
					id={rest.id}
					name="accordion"
					hidden
					style={undefined}
				/>
				<label htmlFor={rest.id} className={styles.header}>
					<label htmlFor={rest.id}>{label}</label>
					<div className={styles.icon}>
						<KeyboardArrowLeftIcon />
					</div>
				</label>
				<div className={styles.content}>{children}</div>
			</div>
		)
	}
)

// packages/feflow/src/lib/components/accordion/Accordion.svelte
<script lang="ts">
	import type { HTMLInputAttributes } from "svelte/elements"
	import type { VariantType } from "@dxdns/feflow-core/types"
	import { KeyboardArrowLeftIcon } from "../../icons/index.js"
	import { classMapUtil } from "@dxdns/feflow-core/utils"
	import styles from "./Accordion.module.css"

	interface Props extends HTMLInputAttributes {
		label: string
		variant?: VariantType
	}

	let {
		class: className = "",
		label,
		variant,
		children,
		...rest
	}: Props = $props()
</script>

<div
	class={classMapUtil(
		className,
		[className, styles],
		[variant, styles],
		styles.accordion
	)}
	style={rest.style}
>
	<input
		{...rest}
		class={styles.controller}
		type="radio"
		id={rest.id}
		name="accordion"
		hidden
		style={undefined}
	/>
	<label for={rest.id} class={styles.header}>
		<label for={rest.id}>{label}</label>
		<div class={styles.icon}>
			<KeyboardArrowLeftIcon />
		</div>
	</label>
	<div class={styles.content}>
		{@render children?.()}
	</div>
</div>
