// packages/svelte/src/lib/components/bottom-sheet/BottomSheet.svelte
<script lang="ts">
	import { bottomSheetAction } from "@dxdns/feflow-core/actions"
	import { classMapUtil } from "@dxdns/feflow-core/utils"
	import type { HTMLAttributes } from "svelte/elements"
	import type { BottomSheetType } from "@dxdns/feflow-core/types"
	import styles from "@dxdns/feflow-core/styles/BottomSheet.module.css"

	interface Props
		extends Omit<HTMLAttributes<HTMLDivElement>, "color">,
			BottomSheetType {}

	let {
		class: className = "",
		isOpen,
		handleClose,
		children,
		...rest
	}: Props = $props()
</script>

<div
	use:bottomSheetAction={{ handleClose, styles }}
	class={classMapUtil(className, [className, styles], styles.bottomSheet, {
		[styles.show]: isOpen
	})}
>
	<div {...rest} class={styles.content}>
		<div class={styles.header}>
			<div class={styles.dragIcon}>
				<span></span>
			</div>
		</div>

		<div class={styles.wrapper}>
			{@render children?.()}
		</div>
	</div>
</div>

// packages/react/src/lib/components/bottom-sheet/BottomSheet.tsx
import { classMapUtil } from "@dxdns/feflow-core/utils"
import { forwardRef, HTMLAttributes } from "react"
import { useAction } from "../../utils"
import { bottomSheetAction } from "@dxdns/feflow-core/actions"
import type { BottomSheetType } from "@dxdns/feflow-core/types"
import styles from "@dxdns/feflow-core/styles/BottomSheet.module.css"

interface Props
	extends Omit<HTMLAttributes<HTMLDivElement>, "color">,
		BottomSheetType {}

export default forwardRef<HTMLDivElement, Props>(
	({ className = "", isOpen, handleClose, children, ...rest }, _ref) => {
		const actionRef = useAction<HTMLDivElement, { handleClose: () => void }>(
			bottomSheetAction,
			{ handleClose }
		)

		return (
			<div
				{...rest}
				ref={actionRef}
				className={classMapUtil(
					className,
					[className, styles],
					styles.bottomSheet,
					{
						[styles.show]: isOpen
					}
				)}
			>
				<div className={styles.content}>
					<div className={styles.header}>
						<div className={styles.dragIcon}>
							<span></span>
						</div>
					</div>

					<div className={styles.wrapper}>{children}</div>
				</div>
			</div>
		)
	}
)
