// packages/react/src/lib/components/toast/Toast.tsx
import {
	forwardRef,
	HTMLAttributes,
	useContext,
	useEffect,
	useState
} from "react"
import type { ToastType } from "@dxdns-kit/core/types"
import { closeIcon } from "@dxdns-kit/core/icons"
import { classMapUtil } from "@dxdns-kit/core/utils"
import { Alert } from "../alert"
import { Button } from "../button"
import { ToastContext } from "../../contexts/ToastContext"
import styles from "@dxdns-kit/core/styles/Toast.module.css"

interface Props
	extends Omit<Omit<HTMLAttributes<HTMLDivElement>, "color">, "id">,
		ToastType {}

export default forwardRef<HTMLDivElement, Props>(
	(
		{
			className = "",
			id,
			message,
			color = "info",
			isClosable = false,
			withProgressLoader = false,
			...rest
		},
		ref
	) => {
		const _toastContext = useContext(ToastContext)
		const toast = _toastContext.getById(id)
		const toastRemaining = toast?.remaining ?? 3000

		const [timerValue, setTimerValue] = useState(toastRemaining)

		const interval = setInterval(() => {
			if (timerValue > 0 && !toast?.paused) {
				setTimerValue(Math.max(timerValue - 100, 0))
			}
		}, 100)

		useEffect(() => {
			return () => {
				clearInterval(interval)
			}
		})

		return (
			<Alert
				{...rest}
				ref={ref}
				className={classMapUtil(className, styles.toast)}
				onMouseEnter={() => {
					_toastContext.pause(id)
				}}
				onMouseLeave={() => {
					_toastContext.resume(id)
				}}
				color={color}
			>
				<div className={styles.wrapper}>
					<div className={styles.message}>{message}</div>
					{
						withProgressLoader && <></>
						// <ProgressLoader
						// 	value={(timerValue / toastRemaining) * 100}
						// 	color={color}
						// />
					}
				</div>
				{isClosable && (
					<Button
						roundedFull
						size="xs"
						style={{
							padding: 0,
							height: "20px",
							minWidth: "20px"
						}}
						onClick={() => {
							_toastContext.remove(id)
						}}
					>
						<svg
							viewBox="0 -960 960 960"
							style={{
								display: "inline-block",
								verticalAlign: "middle",
								fill: "currentcolor",
								width: "16px",
								height: "16px"
							}}
						>
							<path d={closeIcon}></path>
						</svg>
					</Button>
				)}
			</Alert>
		)
	}
)

// packages/svelte/src/lib/components/toast/Toast.svelte
<script lang="ts">
	import type { ToastType } from "@dxdns-kit/core/types"
	import { classMapUtil } from "@dxdns-kit/core/utils"
	import type { HTMLAttributes } from "svelte/elements"
	import Button from "../button/index.js"
	import { Alert } from "../alert/index.js"
	import { toastState } from "../../states/index.js"
	import { onDestroy } from "svelte"
	import ProgressLoader from "../progress-loader/index.js"
	import { closeIcon } from "@dxdns-kit/core/icons"
	import styles from "@dxdns-kit/core/styles/Toast.module.css"

	interface Props
		extends Omit<Omit<HTMLAttributes<HTMLDivElement>, "color">, "id">,
			ToastType {}

	let {
		class: className = "",
		id,
		message,
		isClosable = false,
		handleClose,
		...rest
	}: Props = $props()

	const _toastState = toastState()
	const toast = _toastState._getById(id)
	const toastRemaining = toast?.remaining ?? 3000
	let timerValue = $state(toastRemaining)

	const interval = setInterval(() => {
		if (timerValue > 0 && !toast?.paused) {
			timerValue = Math.max(timerValue - 100, 0)
		}
	}, 100)

	onDestroy(() => {
		clearInterval(interval)
	})
</script>

<Alert
	{...rest}
	class={classMapUtil(className, styles.toast)}
	onmouseenter={() => {
		_toastState.pause(id)
	}}
	onmouseleave={() => {
		_toastState.resume(id)
	}}
>
	<div class={styles.wrapper}>
		<div class={styles.message}>
			{message}
		</div>
		{#if rest.withProgressLoader}
			<ProgressLoader
				value={(timerValue / toastRemaining) * 100}
				color={rest.color}
			/>
		{/if}
	</div>
	{#if isClosable}
		<Button
			roundedFull
			size="xs"
			style="
			padding: 0; 
			height: 20px;
			min-width: 20px;
			"
			onclick={handleClose}
		>
			<svg
				viewBox="0 -960 960 960"
				style="
				display: inline-block; 
				vertical-align: middle;
				fill: currentColor;
				width: 16px;
				height: 16px;
				"
			>
				<path d={closeIcon}></path>
			</svg>
		</Button>
	{/if}
</Alert>
