// packages/react/src/lib/components/feflow-provider/FeflowProvider.tsx
import {
	useState,
	useMemo,
	useRef,
	useEffect,
	type PropsWithChildren
} from "react"
import { Constants } from "@dxdns/feflow-core"
import {
	mergeObjectUtil,
	themeConfigUtil,
	themeModeUtil
} from "@dxdns/feflow-core/utils"
import type {
	BreakpointType,
	ThemeColorType,
	ThemeConfigType,
	ThemeModeType
} from "@dxdns/feflow-core/types"
import { ThemeConfigContext } from "../../contexts"
// @ts-ignore
import rawStyle from "@dxdns/feflow-core/styles/FeflowProvider.css?raw"

type Props = PropsWithChildren & {
	/** @deprecated Use `theme` instead */
	customTheme?: ThemeConfigType

	theme?: ThemeConfigType

	/** @deprecated Use `defaultThemeMode` instead */
	defaultMode?: ThemeModeType

	defaultThemeMode?: ThemeModeType
}

export default function ({
	children,
	customTheme,
	theme,
	defaultMode = "light",
	defaultThemeMode = "light"
}: Props) {
	const [mode, setMode] = useState<ThemeModeType>("light")
	const [colors, setColors] = useState<ThemeColorType>(
		Constants.themeConfigDefault.light
	)

	const _setMode = (t: ThemeModeType) => setMode(t)
	const _setColors = (t: ThemeModeType) =>
		setColors(Constants.themeConfigDefault[t])

	const setThemeMode = (t: ThemeModeType) => {
		_setMode(t)
		_setColors(t)
	}

	const getMode = () => mode
	const getColors = () => Constants.themeConfigDefault[mode]

	const { getThemeModeFromAttr, toggleThemeMode } = themeModeUtil()

	const value = useMemo(
		() => ({
			colors: getColors(),
			mode: getMode(),
			toggle: () => {
				toggleThemeMode((t) => {
					setThemeMode(t)
				})
			}
		}),
		[mode, colors]
	)

	const observer = useRef<MutationObserver | null>(null)

	const { themeConfigToCssString, breakpointConfigToCssString } =
		themeConfigUtil()

	const themeStyle = themeConfigToCssString(
		mergeObjectUtil(
			Constants.themeConfigDefault,
			customTheme?.colors || theme?.colors || {}
		) as ThemeConfigType
	)

	const breakpointStyle = breakpointConfigToCssString(
		mergeObjectUtil(
			Constants.breakpoints,
			customTheme?.breakpoints || theme?.breakpoints || {}
		) as Record<BreakpointType, string>
	)

	useEffect(() => {
		const theme =
			localStorage.getItem(Constants.THEME_STORAGE) ||
			(defaultMode ?? defaultThemeMode)
		document.documentElement.setAttribute(Constants.THEME_ATTR, theme)
		document.documentElement.style.colorScheme = theme
		setThemeMode(theme as ThemeModeType)
	}, [])

	useEffect(() => {
		observer.current = new MutationObserver((records) => {
			for (const mutation of records) {
				if (
					mutation.type === "attributes" &&
					mutation.attributeName === Constants.THEME_ATTR
				) {
					const themeMode = getThemeModeFromAttr()
					setThemeMode(themeMode)
				}
			}
		})

		const rootElement = document.documentElement
		observer.current.observe(rootElement, {
			attributes: true,
			attributeFilter: [Constants.THEME_ATTR]
		})

		return () => {
			observer.current?.disconnect()
		}
	}, [])

	return (
		<>
			<meta name="x-library-name" content="feflow" />
			<div
				dangerouslySetInnerHTML={{
					__html: themeStyle
				}}
			></div>

			<div
				dangerouslySetInnerHTML={{
					__html: breakpointStyle
				}}
			></div>

			<style
				dangerouslySetInnerHTML={{
					__html: rawStyle
				}}
			/>

			<ThemeConfigContext.Provider value={value}>
				{children}
			</ThemeConfigContext.Provider>
		</>
	)
}

// packages/svelte/src/lib/components/feflow-provider/FeflowProvider.svelte
<script lang="ts">
	import { onDestroy, onMount, type Snippet } from "svelte"
	import { Constants } from "@dxdns/feflow-core"
	import type {
		BreakpointType,
		ThemeConfigType,
		ThemeModeType
	} from "@dxdns/feflow-core/types"
	import {
		mergeObjectUtil,
		themeConfigUtil,
		themeModeUtil
	} from "@dxdns/feflow-core/utils"
	import { themeConfigState } from "../../states/index.js"
	import rawStyle from "@dxdns/feflow-core/styles/FeflowProvider.css?raw"
	void rawStyle

	interface Props {
		/** @deprecated Use `theme` instead */
		customTheme?: ThemeConfigType

		theme?: ThemeConfigType

		/** @deprecated Use `defaultThemeMode` instead */
		defaultMode?: ThemeModeType

		defaultThemeMode?: ThemeModeType
		children: Snippet<[]>
	}

	let {
		customTheme,
		theme,
		defaultMode = "light",
		defaultThemeMode = "light",
		children
	}: Props = $props()

	let observer: MutationObserver | undefined = $state()

	const { themeConfigToCssString, breakpointConfigToCssString } =
		themeConfigUtil()

	const themeStyle = themeConfigToCssString(
		mergeObjectUtil(
			Constants.themeConfigDefault,
			customTheme?.colors || theme?.colors || {}
		) as ThemeConfigType
	)

	const breakpointStyle = breakpointConfigToCssString(
		mergeObjectUtil(
			Constants.breakpoints,
			customTheme?.breakpoints || theme?.breakpoints || {}
		) as Record<BreakpointType, string>
	)

	const { getThemeModeFromAttr } = themeModeUtil()
	const themeConfig = themeConfigState()

	onMount(() => {
		const themeMode = getThemeModeFromAttr()
		themeConfig.setThemeMode(themeMode)

		observer = new MutationObserver((records) => {
			for (const mutation of records) {
				if (
					mutation.type === "attributes" &&
					mutation.attributeName === Constants.THEME_ATTR
				) {
					const themeMode = getThemeModeFromAttr()
					themeConfig.setThemeMode(themeMode)
				}
			}
		})

		const rootElement = document.documentElement
		observer.observe(rootElement, {
			attributes: true,
			attributeFilter: [Constants.THEME_ATTR]
		})
	})

	onDestroy(() => {
		observer?.disconnect()
	})
</script>

<svelte:head>
	<meta name="x-library-name" content="feflow" />

	{@html `
	<script>
		(function () {
			const theme = localStorage.getItem("${Constants.THEME_STORAGE}") || "${defaultMode ?? defaultThemeMode}";
			document.documentElement.setAttribute("${Constants.THEME_ATTR}", theme);
			document.documentElement.style.colorScheme = theme;
		})()
	</script>
	`}

	{@html themeStyle}
	{@html breakpointStyle}

	{@html `<style>${rawStyle}</style>`}
</svelte:head>

{@render children?.()}
