// packages/svelte/src/lib/components/drawer/DrawerContent.svelte
<script lang="ts">
	import { classMapUtil } from "@navnex-kit/core/utils"
	import type { HTMLAttributes } from "svelte/elements"
	import styles from "@navnex-kit/core/styles/DrawerContent.module.css"

	interface Props extends HTMLAttributes<HTMLDivElement> {}

	let { class: className = "", children, ...rest }: Props = $props()
</script>

<div
	{...rest}
	class={classMapUtil(className, [className, styles], styles.drawerContent)}
>
	{@render children?.()}
</div>

// packages/react/src/lib/components/drawer/DrawerContent.tsx
import { forwardRef, HTMLAttributes } from "react"
import styles from "@navnex-kit/core/styles/DrawerContent.module.css"
import { classMapUtil } from "@navnex-kit/core/utils"

export interface Props extends HTMLAttributes<HTMLDivElement> {}

export default forwardRef<HTMLDivElement, Props>((props, ref) => {
	const { className = "", children, ...rest } = props

	return (
		<div
			{...rest}
			ref={ref}
			className={classMapUtil(
				className,
				[className, styles],
				styles.drawerContent
			)}
		>
			{children}
		</div>
	)
})
