// src/lib/components/drawer-header/DrawerHeader.svelte
<script lang="ts">
	import type { ClassValue, HTMLAttributes } from "svelte/elements"
	import classMapUtil from "../../utils/classMapUtil.js"
	import styles from "./DrawerHeader.module.css"
	import IconButton from "../icon-button/index.js"
	import type { Snippet } from "svelte"

	interface Props extends HTMLAttributes<HTMLDivElement> {
		class?: ClassValue
		handleClick: () => void
		logo: Snippet
		closeIcon: Snippet
	}

	let {
		class: className = "",
		handleClick,
		logo,
		closeIcon,
		...rest
	}: Props = $props()
</script>

<div
	class={classMapUtil({
		[className as string]: true,
		[styles.drawerHeader]: true
	})}
	{...rest}
>
	<a href="/app" title="logo">
		{@render logo?.()}
	</a>
	<IconButton class={styles.buttonClose} onclick={handleClick}>
		{@render closeIcon?.()}
	</IconButton>
</div>

// packages/react/src/lib/components/drawer/DrawerHeader.tsx
import { forwardRef, HTMLAttributes } from "react"
import { classMapUtil } from "@feflow-ui/core/utils"
import styles from "@feflow-ui/core/styles/DrawerHeader.module.css"
import { Button } from "../button"
import { CloseIcon } from "../../icons/index.js"

export interface Props extends HTMLAttributes<HTMLDivElement> {
	handleClose?: () => void
}

export default forwardRef<HTMLDivElement, Props>((props, ref) => {
	const { className = "", handleClose, children, ...rest } = props

	return (
		<div
			{...rest}
			ref={ref}
			className={classMapUtil(
				className,
				[className, styles],
				styles.drawerHeader,
				{
					[styles.isClosable]: Boolean(handleClose)
				}
			)}
		>
			{children}
			{handleClose && (
				<Button
					variant="text"
					className={styles.buttonClose}
					onClick={handleClose}
				>
					<CloseIcon />
				</Button>
			)}
		</div>
	)
})
