// packages/react/src/lib/components/checkbox/Checkbox.tsx
import { forwardRef, InputHTMLAttributes } from "react"
import type { SizeType } from "@feflow-ui/core/types"
import { classMapUtil } from "@feflow-ui/core/utils"
import { CheckmarkIcon } from "../../icons"
import styles from "@feflow-ui/core/styles/Checkbox.module.css"

interface Props
	extends Omit<Omit<InputHTMLAttributes<HTMLInputElement>, "size">, "type"> {
	size?: SizeType
}

export default forwardRef<HTMLInputElement, Props>(
	({ className = "", size = "sm", ...rest }, ref) => {
		return (
			<label
				className={classMapUtil(
					className,
					[className, styles],
					styles.checkbox,
					[size, styles],
					{
						["text-muted"]: rest.disabled
					}
				)}
			>
				<input
					{...rest}
					ref={ref}
					readOnly={rest.readOnly ?? rest.checked}
					type="checkbox"
				/>
				<div className={styles.wrapper}>
					<div className={styles.bg}></div>
					<CheckmarkIcon className={styles.icon} />
				</div>
				{rest["aria-label"]}
			</label>
		)
	}
)

// packages/svelte/src/lib/components/checkbox/Checkbox.svelte
<script lang="ts">
	import { classMapUtil } from "@feflow-ui/core/utils"
	import type { HTMLInputAttributes } from "svelte/elements"
	import type { SizeType } from "@feflow-ui/core/types"
	import styles from "@feflow-ui/core/styles/Checkbox.module.css"
	import { CheckmarkIcon } from "../../icons/index.js"

	interface Props extends Omit<Omit<HTMLInputAttributes, "size">, "type"> {
		size?: SizeType
	}

	let { class: className = "", size = "sm", ...rest }: Props = $props()
</script>

<label
	class={classMapUtil(
		className,
		[className, styles],
		styles.checkbox,
		[size, styles],
		{
			["text-muted"]: rest.disabled
		}
	)}
>
	<input {...rest} readonly={rest.readonly ?? rest.checked} type="checkbox" />
	<div class={styles.wrapper}>
		<div class={styles.bg}></div>
		<CheckmarkIcon class={styles.icon} />
	</div>
	{rest["aria-label"]}
</label>
