// packages/feflow/src/lib/components/image/Image.svelte
<script lang="ts">
	import { lazyLoadAction } from "../../actions/index.js"
	import type { HTMLImgAttributes } from "svelte/elements"
	import { mergeStyleUtil, classMapUtil } from "@dxdns/feflow-core/utils"

	interface Props extends Omit<HTMLImgAttributes, "src"> {
		lazy?: boolean
		dataSrc: string
		hover?: { transition?: "none" | "scale" }
		fallback?: string
	}

	let {
		class: className = "",
		lazy = false,
		dataSrc,
		hover = { transition: "none" },
		fallback,
		children,
		...rest
	}: Props = $props()

	let hasError = $state(false)

	function handleError() {
		hasError = true
	}

	const hasTransition = hover && hover.transition !== "none"
	const transitionDefault = "opacity 1s ease-in-out"
	const transitionKey = "--transition"

	const style = mergeStyleUtil(
		hasTransition
			? `${transitionKey}: ${transitionDefault}, ${hover?.transition} 0.3s ease-in-out;`
			: `${transitionKey}: ${transitionDefault}`,
		`transition: var(${transitionKey});`,
		rest.style
	)
</script>

{#if lazy}
	<img
		{...rest}
		class={classMapUtil(className, {
			[hover.transition!]: hasTransition
		})}
		{style}
		data-src={dataSrc}
		data-fallback={fallback}
		use:lazyLoadAction
		loading="lazy"
		decoding="async"
		onerror={handleError}
	/>
{:else}
	<img
		{...rest}
		class={className}
		src={hasError ? (fallback ?? dataSrc) : dataSrc}
		onerror={handleError}
	/>
{/if}

<style>
	.scale:hover {
		scale: 1.125;
	}
</style>

// packages/react/src/lib/components/image/Image.tsx
import type { HTMLAttrAnchor, ImageType } from "@dxdns/feflow-core/types"
import { forwardRef, ImgHTMLAttributes } from "react"
import { useAction } from "../../utils"
import { imageAction } from "@dxdns/feflow-core/actions"

interface Props
	extends Omit<ImgHTMLAttributes<Omit<HTMLImageElement, "src">>, "color">,
		ImageType,
		HTMLAttrAnchor {}

export default forwardRef<HTMLImageElement, Props>(
	({ className = "", lazy = false, dataSrc, fallback, ...rest }, _ref) => {
		const actionRef = useAction<
			HTMLImageElement,
			Parameters<typeof imageAction>[1]
		>(imageAction, { lazy })

		return (
			<img
				{...rest}
				ref={actionRef}
				className={className}
				data-src={dataSrc}
				data-fallback={fallback}
				loading={lazy ? "lazy" : undefined}
				decoding={lazy ? "async" : undefined}
			/>
		)
	}
)
