// packages/svelte/src/lib/components/card/Card.svelte
<script lang="ts">
	import type {
		HTMLAttributeAnchorTarget,
		HTMLAttributes
	} from "svelte/elements"
	import { classMapUtil, mergeStyleUtil } from "@dxdns/feflow-core/utils"
	import { glowOnHoverAction } from "@dxdns/feflow-core/actions"
	import type { CardType } from "@dxdns/feflow-core/types"
	import styles from "@dxdns/feflow-core/styles/Card.module.css"

	interface Props
		extends Omit<HTMLAttributes<HTMLDivElement>, "color">,
			CardType {
		target?: HTMLAttributeAnchorTarget
	}

	let {
		class: className = "",
		isTranslucent = false,
		glowOnHover = false,
		animatedBorder = false,
		variant = "outlined",
		href,
		target = "_self",
		children,
		...rest
	}: Props = $props()
</script>

{#snippet component()}
	<div
		{...rest}
		role="button"
		class={classMapUtil(
			className,
			[className, styles],
			[variant, styles],
			styles.card,
			{
				[styles.isTranslucent]: isTranslucent,
				[styles.animatedBorder]: animatedBorder
			}
		)}
		style={mergeStyleUtil(href ? "cursor: pointer;" : "", rest.style)}
		onclick={href ? () => window.open(href, target) : rest.onclick}
	>
		{@render children?.()}
	</div>
{/snippet}

{#if glowOnHover}
	<div use:glowOnHoverAction>
		{@render component()}
	</div>
{:else}
	{@render component()}
{/if}

// packages/react/src/lib/components/card/Card.tsx
import type { CardType } from "@dxdns/feflow-core/types"
import { classMapUtil } from "@dxdns/feflow-core/utils"
import { forwardRef, HTMLAttributeAnchorTarget, HTMLAttributes } from "react"
import { useAction } from "../../utils"
import { glowOnHoverAction } from "@dxdns/feflow-core/actions"
import styles from "@dxdns/feflow-core/styles/Card.module.css"

interface Props
	extends Omit<HTMLAttributes<HTMLDivElement>, "color">,
		CardType {
	target?: HTMLAttributeAnchorTarget
}

export default forwardRef<HTMLDivElement, Props>(
	(
		{
			className,
			isTranslucent = false,
			glowOnHover = false,
			variant = "outlined",
			href,
			target = "_self",
			children,
			...rest
		},
		ref
	) => {
		const actionRef = useAction<HTMLDivElement>(glowOnHoverAction)

		return (
			<div ref={glowOnHover ? actionRef : undefined}>
				<div
					{...rest}
					ref={ref}
					role="button"
					className={classMapUtil(
						className,
						[className, styles],
						[variant, styles],
						styles.card,
						{
							[styles.isTranslucent]: isTranslucent
						}
					)}
					style={{ cursor: href ? "pointer" : "default", ...rest.style }}
					onClick={href ? () => window.open(href, target) : rest.onClick}
				>
					{children}
				</div>
			</div>
		)
	}
)
