// packages/svelte/src/lib/components/text/Text.svelte
<script lang="ts" generics="T extends HTMLTagTextType">
	import { classMapUtil, mergeStyleUtil } from "@dxdns-kit/core/utils"
	import type { HTMLAttributes } from "svelte/elements"
	import styles from "./Text.module.css"
	import type {
		HTMLTagMap,
		HTMLTagTextType,
		TextType
	} from "@dxdns-kit/core/types"

	interface Props<T extends HTMLTagTextType>
		extends HTMLAttributes<HTMLTagMap[T]>,
			TextType {}
	let {
		class: className = "",
		as = "p",
		lines = Infinity,
		children,
		...rest
	}: Props<T> = $props()
</script>

<svelte:element
	this={as}
	{...rest}
	class={classMapUtil(className, [className, styles], styles.text)}
	style={mergeStyleUtil(`--lines: ${lines};`, rest.style)}
>
	{@render children?.()}
</svelte:element>

// packages/react/src/lib/components/text/Text.tsx
import { CSSProperties, forwardRef, HTMLAttributes, Ref } from "react"
import type {
	HTMLTagMap,
	HTMLTagTextType,
	TextType
} from "@dxdns-kit/core/types"
import { classMapUtil } from "@dxdns-kit/core/utils"
import styles from "@dxdns-kit/core/styles/Text.module.css"

interface Props<T extends HTMLTagTextType>
	extends HTMLAttributes<HTMLTagMap[T]>,
		TextType {}

export default forwardRef(
	<T extends HTMLTagTextType = "p">(
		{ className = "", as = "p", lines = Infinity, children, ...rest }: Props<T>,
		ref?: Ref<HTMLParagraphElement>
	) => {
		const Component = as

		return (
			<Component
				{...rest}
				ref={ref}
				className={classMapUtil(className, [className, styles], styles.text)}
				style={{ ["--lines"]: lines, ...rest.style } as CSSProperties}
			>
				{children}
			</Component>
		)
	}
)
