// packages/react/src/lib/components/badge/Badge.tsx
import { forwardRef, HTMLAttributes } from "react"
import { classMapUtil } from "@feflow-ui/core/utils"
import styles from "@feflow-ui/core/styles/Badge.module.css"
import type { BadgeType } from "@feflow-ui/core/types"

interface Props extends HTMLAttributes<HTMLSpanElement>, BadgeType {}

export default forwardRef<HTMLDivElement, Props>(
	(
		{
			className = "",
			size = "xs",
			variant = "contained",
			roundedFull = false,
			children,
			...rest
		},
		ref
	) => {
		return (
			<span
				{...rest}
				ref={ref}
				className={classMapUtil(
					className,
					[className, styles],
					styles.badge,
					[size, styles],
					[variant, styles],
					{
						[styles.roundedFull]: roundedFull
					}
				)}
			>
				{children}
			</span>
		)
	}
)

// src/lib/components/badge/Badge.svelte
<script lang="ts">
  import type { HTMLAttributes } from "svelte/elements"
  import styles from "./Badge.module.css"
  import type { SizeType, VariantType } from "../../types/index.js"
  import classMapUtil from "../../utils/classMapUtil.js"

  interface Props extends HTMLAttributes<HTMLSpanElement> {
    size?: SizeType
    variant?: VariantType
  }

  let {
    class: className = "",
    size = "sm",
    variant = "contained",
    children,
    ...rest
  }: Props = $props()
</script>

<span
  {...rest}
  class={classMapUtil({
    [className as string]: true,
    [styles[size]]: true,
    [styles[variant]]: true,
    [styles.badge]: true,
  })}
>
  {@render children?.()}
</span>
