// packages/react/src/lib/components/checkbox/Checkbox.tsx
import { forwardRef, InputHTMLAttributes } from "react"
import type { SizeType } from "@feflow-ui/core/types"
import { classMapUtil } from "@feflow-ui/core/utils"
import { checkmarkIcon } from "@feflow-ui/core/icons"
import styles from "@feflow-ui/core/styles/Checkbox.module.css"

interface Props
	extends Omit<Omit<InputHTMLAttributes<HTMLInputElement>, "size">, "type"> {
	size?: SizeType
}

export default forwardRef<HTMLInputElement, Props>(
	({ className = "", size = "sm", ...rest }, ref) => {
		return (
			<label
				className={classMapUtil(
					className,
					[className, styles],
					styles.checkbox,
					[size, styles],
					{
						["text-muted"]: rest.disabled
					}
				)}
			>
				<input
					{...rest}
					ref={ref}
					readOnly={rest.readOnly ?? rest.checked}
					type="checkbox"
				/>
				<div className={styles.wrapper}>
					<div className={styles.bg}></div>
					<svg
						className={styles.icon}
						viewBox="0 0 24 24"
						style={{
							display: "inline-block",
							verticalAlign: "middle",
							width: "24px",
							height: "24px"
						}}
					>
						<path
							stroke-linejoin="round"
							stroke-linecap="round"
							stroke-width="3"
							stroke="currentColor"
							d={checkmarkIcon}
						></path>
					</svg>
				</div>
				{rest["aria-label"]}
			</label>
		)
	}
)

// packages/feflow/src/lib/components/checkbox/Checkbox.svelte
<script lang="ts">
	import { classMapUtil } from "@dxdns/feflow-core/utils"
	import styles from "./Checkbox.module.css"
	import type { HTMLInputAttributes } from "svelte/elements"
	import type { SizeType } from "../../types/index.js"

	interface Props extends Omit<Omit<HTMLInputAttributes, "size">, "type"> {
		size?: SizeType
	}

	let { class: className = "", size = "sm", ...rest }: Props = $props()
</script>

<label
	class={classMapUtil(
		className,
		[className, styles],
		styles.checkbox,
		[size, styles],
		{
			["text-muted"]: rest.disabled
		}
	)}
>
	<input type="checkbox" {...rest} />
	<div class={styles.wrapper}>
		<div class={styles.bg}></div>
		<svg fill="none" viewBox="0 0 24 24" class={styles.icon}>
			<path
				stroke-linejoin="round"
				stroke-linecap="round"
				stroke-width="3"
				stroke="currentColor"
				d="M4 12L10 18L20 6"
				class={styles.checkPath}
			></path>
		</svg>
	</div>
	{rest["aria-label"]}
</label>
