// src/lib/components/switch/Switch.svelte
<script lang="ts">
  import type { SizeType } from "../../types/index.js"
  import styles from "./Switch.module.css"
  import type { HTMLInputAttributes } from "svelte/elements"
  import classMapUtil from "../../utils/classMapUtil.js"

  interface Props extends Omit<HTMLInputAttributes, "size"> {
    size?: SizeType
  }

  let { class: className = "", size = "sm", ...rest }: Props = $props()
</script>

<div class={styles.switch}>
  <label
    class={classMapUtil({
      [className as string]: true,
      [styles.content]: true,
      [`text-${size}`]: true,
    })}
  >
    <input {...rest} type="checkbox" />
    <span class={styles.slider}></span>
  </label>
  {rest["aria-label"]}
</div>

// packages/react/src/lib/components/switch/Switch.tsx
import type { SwitchType } from "@feflow-ui/core/types"
import { classMapUtil, getPropValueUtil } from "@feflow-ui/core/utils"
import {
	CSSProperties,
	forwardRef,
	InputHTMLAttributes,
	ReactNode
} from "react"
import styles from "@feflow-ui/core/styles/Switch.module.css"

interface Props
	extends Omit<InputHTMLAttributes<HTMLInputElement>, "size">,
		SwitchType {
	label?: string | ReactNode
}

export default forwardRef<HTMLInputElement, Props>(
	(
		{
			className = "",
			size = "sm",
			label,
			indicatorColor = {
				unchecked: "var(--ff-on-surface)",
				checked: "var(--ff-on-primary)"
			},
			children,
			...rest
		},
		ref
	) => {
		const uncheckedColor = getPropValueUtil<
			{ unchecked?: string },
			"unchecked"
		>(indicatorColor, "unchecked", "var(--ff-on-surface)")

		const checkedColor = getPropValueUtil<{ checked?: string }, "checked">(
			indicatorColor,
			"checked",
			"var(--ff-on-primary)"
		)

		return (
			<div className={styles.switch}>
				<label
					htmlFor={rest.id}
					className={classMapUtil(
						className,
						[className, styles],
						[size, styles],
						styles.content
					)}
				>
					<input {...rest} ref={ref} hidden style={undefined} type="checkbox" />
					<span
						className={styles.slider}
						style={
							{
								["--bg-unchecked"]: uncheckedColor,
								["--bg-checked"]: checkedColor,
								...rest.style
							} as CSSProperties
						}
					>
						{children}
					</span>
				</label>
				{label}
			</div>
		)
	}
)
