// packages/feflow/src/lib/components/switch/Switch.svelte
<script lang="ts">
	import type { SizeType } from "../../types/index.js"
	import styles from "./Switch.module.css"
	import type { HTMLInputAttributes } from "svelte/elements"
	import { classMapUtil } from "@dxdns/feflow-core/utils"
	import type { Snippet } from "svelte"
	import { mergeStyleUtil, getPropValueUtil } from "@dxdns/feflow-core/utils"

	interface Props extends Omit<Omit<HTMLInputAttributes, "size">, "type"> {
		size?: SizeType
		label?: string | Snippet<[]>
		indicatorColor?:
			| boolean
			| {
					unchecked?: string
					checked?: string
			  }
	}

	let {
		class: className = "",
		size = "sm",
		label,
		indicatorColor = {
			unchecked: "var(--ff-on-surface)",
			checked: "var(--ff-on-primary)"
		},
		children,
		...rest
	}: Props = $props()

	const uncheckedColor = getPropValueUtil<{ unchecked?: string }, "unchecked">(
		indicatorColor,
		"unchecked",
		"var(--ff-on-surface)"
	)

	const checkedColor = getPropValueUtil<{ checked?: string }, "checked">(
		indicatorColor,
		"checked",
		"var(--ff-on-primary)"
	)
</script>

<div class={styles.switch}>
	<label
		class={classMapUtil(
			className,
			[className, styles],
			[size, styles],
			styles.content
		)}
	>
		<input {...rest} style={undefined} type="checkbox" hidden />
		<span
			class={styles.slider}
			style={mergeStyleUtil(
				`--indicator-color-unchecked: ${uncheckedColor};`,
				`--indicator-color-checked: ${checkedColor};`,
				rest.style
			)}
		>
			{@render children?.()}
		</span>
	</label>
	{#if typeof label === "string"}
		{label}
	{:else}
		{@render label?.()}
	{/if}
</div>

// packages/react/src/lib/components/switch/Switch.tsx
import type { SwitchType } from "@dxdns/feflow-core/types"
import { classMapUtil, getPropValueUtil } from "@dxdns/feflow-core/utils"
import {
	CSSProperties,
	forwardRef,
	InputHTMLAttributes,
	ReactNode
} from "react"
import styles from "@dxdns/feflow-core/styles/Switch.module.css"

interface Props
	extends Omit<InputHTMLAttributes<HTMLInputElement>, "size">,
		SwitchType {
	label?: string | ReactNode
}

export default forwardRef<HTMLInputElement, Props>(
	(
		{
			className = "",
			size = "sm",
			label,
			indicatorColor = {
				unchecked: "var(--ff-on-surface)",
				checked: "var(--ff-on-primary)"
			},
			children,
			...rest
		},
		ref
	) => {
		const uncheckedColor = getPropValueUtil<
			{ unchecked?: string },
			"unchecked"
		>(indicatorColor, "unchecked", "var(--ff-on-surface)")

		const checkedColor = getPropValueUtil<{ checked?: string }, "checked">(
			indicatorColor,
			"checked",
			"var(--ff-on-primary)"
		)

		return (
			<div className={styles.switch}>
				<label
					htmlFor={rest.id}
					className={classMapUtil(
						className,
						[className, styles],
						[size, styles],
						styles.content
					)}
				>
					<input {...rest} ref={ref} hidden style={undefined} type="checkbox" />
					<span
						className={styles.slider}
						style={
							{
								["--bg-unchecked"]: uncheckedColor,
								["--bg-checked"]: checkedColor
							} as CSSProperties
						}
					>
						{children}
					</span>
				</label>
				{label}
			</div>
		)
	}
)
