// packages/feflow/src/lib/components/spinner/Spinner.svelte
<script lang="ts">
	import type { SizeType } from "../../types/index.js"
	import { classMapUtil } from "@dxdns/feflow-core/utils"
	import type { HTMLAttributes } from "svelte/elements"
	import styles from "./Spinner.module.css"

	interface Props extends HTMLAttributes<HTMLSpanElement> {
		size?: SizeType
	}

	let { class: className = "", size = "sm", ...rest }: Props = $props()
</script>

<span
	{...rest}
	class={classMapUtil(
		className,
		[className, styles],
		[size, styles],
		styles.spinner
	)}
></span>

// packages/react/src/lib/components/spinner/Spinner.tsx
import type { SizeType } from "@feflow/core/types"
import React from "react"
import { classMapUtil } from "@feflow/core/utils"
import styles from "@feflow/core/styles/Spinner.module.css"

type Props = React.HTMLAttributes<HTMLSpanElement> & {
	size?: SizeType
}

export default React.forwardRef<HTMLSpanElement, Props>((props, ref) => {
	const { className, size = "sm", ...rest } = props

	return (
		<span
			ref={ref}
			{...rest}
			className={classMapUtil(
				className,
				[className, styles],
				[size, styles],
				styles.spinner
			)}
		></span>
	)
})
