// packages/svelte/src/lib/components/gallery/GalleryVideo.svelte
<script lang="ts">
	import { classMapUtil, handleClickUtil } from "@dxdns-kit/core/utils"
	import type {
		GalleryItemType,
		HTMLAttrAnchor,
		VideoType
	} from "@dxdns-kit/core/types"
	import styles from "@dxdns-kit/core/styles/GalleryItem.module.css"
	import type { HTMLVideoAttributes } from "svelte/elements"
	import { Video } from "../video/index.js"
	import { createPortalAction } from "@dxdns-kit/core/actions"
	import Modal from "../modal/index.js"

	type HTMLVideoAttr = Omit<HTMLVideoAttributes, "src">

	interface Props
		extends HTMLVideoAttr,
			GalleryItemType<{}, HTMLVideoAttr>,
			HTMLAttrAnchor,
			VideoType {}

	let {
		class: className = "",
		lazy = false,
		dataSrc,
		href,
		target = "_self",
		download,
		viewer,
		children,
		...rest
	}: Props = $props()

	let isOpen = $state(false)
	let selectedEl: HTMLVideoElement | undefined = $state()

	function handleOpen() {
		isOpen = true
	}

	function handleClose() {
		isOpen = false
		selectedEl = undefined
	}

	function handleClick(e: any) {
		handleClickUtil({
			href,
			download,
			target,
			onClick: () => {
				rest.onclick?.(e)
			}
		})
	}

	function handleVideoClick(
		e: MouseEvent & { currentTarget: EventTarget & HTMLVideoElement }
	) {
		if (viewer) {
			selectedEl = e.currentTarget
			handleOpen()
		}

		handleClick(e)
	}
</script>

{#if viewer && isOpen && selectedEl}
	<div use:createPortalAction>
		<Modal {isOpen} style="border: none;" {handleClose}>
			<Modal.Content
				style="
				text-align: center; 
				overflow: hidden; 
				padding: 0;
				"
			>
				<video
					{...rest}
					{...viewer}
					src={selectedEl.src || selectedEl.querySelector("source")?.src || ""}
				></video>
			</Modal.Content>
		</Modal>
	</div>
{/if}

<figure
	class={classMapUtil(className, [styles, className], styles.galleryItem)}
	style="cursor: {rest.onclick || viewer ? 'pointer' : 'default'};"
>
	<Video
		{...rest}
		class={styles.thumbnail}
		{lazy}
		{dataSrc}
		onclick={handleVideoClick}
	/>

	<figcaption>
		{@render children?.()}
	</figcaption>
</figure>

// packages/react/src/lib/components/gallery/GalleryVideo.tsx
import type {
	GalleryItemType,
	HTMLAttrAnchor,
	VideoType
} from "@dxdns-kit/core/types"
import { classMapUtil, handleClickUtil } from "@dxdns-kit/core/utils"
import {
	forwardRef,
	MouseEvent,
	ReactNode,
	useState,
	VideoHTMLAttributes
} from "react"
import { Video } from "../video"
import { createPortal } from "react-dom"
import Modal from "../modal"
import styles from "@dxdns-kit/core/styles/GalleryItem.module.css"

type HTMLVideoAttr = Omit<VideoHTMLAttributes<HTMLVideoElement>, "src">

interface Props
	extends HTMLVideoAttr,
		GalleryItemType<{}, HTMLVideoAttr>,
		HTMLAttrAnchor,
		VideoType {}

export default forwardRef<HTMLVideoElement, Props>(
	(
		{
			className = "",
			lazy = false,
			dataSrc,
			href,
			target = "_self",
			download,
			viewer,
			children,
			...rest
		},
		ref
	) => {
		const [isOpen, setIsOpen] = useState(false)
		const [selectedEl, setSelectedEl] = useState<ReactNode>(null)

		function handleOpen() {
			setIsOpen(true)
		}

		function handleClose() {
			setIsOpen(false)
			setSelectedEl(null)
		}

		function handleClick(e: any) {
			handleClickUtil({
				href,
				download,
				target,
				onClick: () => {
					rest.onClick?.(e)
				}
			})
		}

		function handleVideoClick(e: MouseEvent<HTMLVideoElement>) {
			if (viewer) {
				const el = e.currentTarget

				const clonedVideo = (
					<video
						{...rest}
						{...viewer}
						src={el.src || el.querySelector("source")?.src || ""}
					/>
				)

				setSelectedEl(clonedVideo)
				handleOpen()
			}

			handleClick(e)
		}

		return (
			<>
				{viewer &&
					isOpen &&
					selectedEl &&
					createPortal(
						<Modal
							isOpen={isOpen}
							style={{ border: "none" }}
							handleClose={handleClose}
						>
							<Modal.Content
								style={{
									textAlign: "center",
									overflow: "hidden",
									padding: 0
								}}
							>
								{selectedEl}
							</Modal.Content>
						</Modal>,
						document.body
					)}

				<figure
					className={classMapUtil(
						className,
						[className, styles],
						styles.galleryItem
					)}
					style={{ cursor: rest.onClick || viewer ? "pointer" : "default" }}
				>
					<Video
						{...rest}
						ref={ref}
						className={styles.thumbnail}
						lazy={lazy}
						dataSrc={dataSrc}
						onClick={handleVideoClick}
					/>

					<figcaption>{children}</figcaption>
				</figure>
			</>
		)
	}
)
