// packages/svelte/src/lib/components/gallery/GalleryItem.svelte
<script lang="ts">
	import {
		classMapUtil,
		handleClickUtil,
		hasKeysUtil,
		videoUtil
	} from "@dxdns/feflow-core/utils"
	import type {
		GalleryItemType,
		GalleryCaptionType,
		HTMLAttrAnchor,
		ImageType,
		GalleryMediaType
	} from "@dxdns/feflow-core/types"
	import type { Snippet } from "svelte"
	import styles from "@dxdns/feflow-core/styles/GalleryItem.module.css"
	import type { HTMLImgAttributes, HTMLVideoAttributes } from "svelte/elements"
	import { Video } from "../video/index.js"
	import { Image } from "../image/index.js"

	interface BaseProps
		extends GalleryItemType<Snippet<[]> | GalleryCaptionType | undefined>,
			HTMLAttrAnchor,
			GalleryMediaType {}

	type ImgProps = Omit<HTMLImgAttributes, "src"> & BaseProps & ImageType
	type VideoProps = Omit<HTMLVideoAttributes, "src"> & BaseProps

	type Props = ImgProps | VideoProps

	let {
		class: className = "",
		lazy = false,
		dataSrc,
		caption,
		href,
		target = "_self",
		download,
		children,
		...rest
	}: Props = $props()

	const { isVideo } = videoUtil()

	function handleClick(e: any) {
		handleClickUtil({
			href,
			download,
			target,
			onClick: () => {
				rest.onclick?.(e)
			}
		})
	}
</script>

<figure
	class={classMapUtil(className, [styles, className], styles.galleryItem)}
>
	{#if isVideo(dataSrc)}
		<Video
			{...rest as HTMLVideoAttributes}
			class={styles.thumbnail}
			{lazy}
			{dataSrc}
			onclick={handleClick}
		/>
	{:else}
		<Image
			{...rest as HTMLImgAttributes}
			class={styles.thumbnail}
			{lazy}
			{dataSrc}
			onclick={handleClick}
		/>
	{/if}

	{#if children}
		{@render children?.()}
	{:else if caption && hasKeysUtil<GalleryCaptionType>(caption)}
		<figcaption class={styles.caption}>
			<h3>{caption.title}</h3>
			<p>{caption.description}</p>
		</figcaption>
	{:else if caption && typeof caption === "function"}
		{@render caption?.()}
	{/if}
</figure>

// packages/react/src/lib/components/gallery/GalleryItem.tsx
import type {
	GalleryCaptionType,
	GalleryItemType,
	GalleryMediaType,
	HTMLAttrAnchor,
	ImageType
} from "@dxdns/feflow-core/types"
import {
	classMapUtil,
	handleClickUtil,
	hasKeysUtil,
	videoUtil
} from "@dxdns/feflow-core/utils"
import {
	forwardRef,
	ImgHTMLAttributes,
	isValidElement,
	ReactNode,
	Ref,
	VideoHTMLAttributes
} from "react"
import { Image } from "../image"
import styles from "@dxdns/feflow-core/styles/GalleryItem.module.css"
import { Video } from "../video"

interface BaseProps
	extends GalleryItemType<ReactNode | GalleryCaptionType | undefined>,
		HTMLAttrAnchor,
		GalleryMediaType {}

type HTMLImageAttr = Omit<ImgHTMLAttributes<HTMLImageElement>, "src">
type ImgProps = HTMLImageAttr & BaseProps & ImageType

type HTMLVideoAttr = Omit<VideoHTMLAttributes<HTMLVideoElement>, "src">
type VideoProps = HTMLVideoAttr & BaseProps

type Props = ImgProps | VideoProps

export default forwardRef<HTMLImageElement | HTMLVideoElement, Props>(
	(
		{
			className = "",
			lazy = false,
			dataSrc,
			caption,
			href,
			target = "_self",
			download,
			children,
			...rest
		},
		ref
	) => {
		const { isVideo } = videoUtil()

		function handleClick(e: any) {
			handleClickUtil({
				href,
				download,
				target,
				onClick: () => {
					rest.onClick?.(e)
				}
			})
		}

		return (
			<figure
				className={classMapUtil(
					className,
					[styles, className],
					styles.galleryItem
				)}
			>
				{isVideo(dataSrc) ? (
					<Video
						{...(rest as HTMLVideoAttr)}
						ref={ref as Ref<HTMLVideoElement>}
						className={styles.thumbnail}
						lazy={lazy}
						dataSrc={dataSrc}
						onClick={handleClick}
					/>
				) : (
					<Image
						{...(rest as HTMLImageAttr)}
						ref={ref as Ref<HTMLImageElement>}
						className={styles.thumbnail}
						lazy={lazy}
						dataSrc={dataSrc}
						onClick={handleClick}
					/>
				)}

				{children ? (
					children
				) : caption && hasKeysUtil<GalleryCaptionType>(caption) ? (
					<figcaption className={styles.caption}>
						<div>
							<h3>{caption.title}</h3>
							<p>{caption.description}</p>
						</div>
					</figcaption>
				) : (
					isValidElement(caption) && caption
				)}
			</figure>
		)
	}
)
