// packages/react/src/lib/components/drawer/Drawer.tsx
import React, { forwardRef } from "react"
import { classMapUtil } from "@dxdns/feflow-core/utils"
import type { DrawerType } from "@dxdns/feflow-core/types"
import styles from "@dxdns/feflow-core/styles/Drawer.module.css"

export interface Props
	extends React.HTMLAttributes<HTMLDivElement>,
		DrawerType {}

export default forwardRef<HTMLDivElement, Props>((props, ref) => {
	const {
		className = "",
		isOpen = false,
		variant = "temporary",
		position = "left",
		children,
		...rest
	} = props

	return (
		<div
			{...rest}
			ref={ref}
			className={classMapUtil(
				className,
				[className, styles],
				styles.drawer,
				[position, styles],
				[variant, styles],
				{
					[styles.show]: isOpen
				}
			)}
		>
			{children}
		</div>
	)
})

// packages/feflow/src/lib/components/drawer/Drawer.svelte
<script lang="ts">
	import type { HTMLAttributes } from "svelte/elements"
	import styles from "./Drawer.module.css"
	import type { PositionNoCenterType } from "../../types/index.js"
	import { classMapUtil } from "@dxdns/feflow-core/utils"

	interface Props extends HTMLAttributes<HTMLDivElement> {
		isOpen: boolean
		variant?: "permanent" | "temporary"
		position?: PositionNoCenterType
	}

	let {
		class: className = "",
		isOpen = false,
		variant = "temporary",
		position = "left",
		children,
		...rest
	}: Props = $props()
</script>

<div
	{...rest}
	class={classMapUtil(
		className,
		[className, styles],
		styles.drawer,
		[position, styles],
		[variant, styles],
		{
			[styles.show]: isOpen
		}
	)}
>
	{@render children?.()}
</div>
