// packages/react/src/lib/components/gallery/Gallery.tsx
import type { GridType } from "@dxdns/feflow-core/types"
import { forwardRef, HTMLAttributes } from "react"
import { Grid } from "../grid/index.js"

interface Props extends HTMLAttributes<HTMLDivElement>, GridType {}

export default forwardRef<HTMLDivElement, Props>(
	({ children, ...rest }, ref) => {
		return (
			<Grid {...rest} ref={ref}>
				{children}
			</Grid>
		)
	}
)

// packages/svelte/src/lib/components/gallery/Gallery.svelte
<script lang="ts">
	import type { HTMLAttributes } from "svelte/elements"
	import type { GridType } from "@dxdns/feflow-core/types"
	import { Grid } from "../grid/index.js"

	interface Props extends HTMLAttributes<HTMLDivElement>, GridType {}

	let { children, ...rest }: Props = $props()
</script>

<Grid {...rest}>
	{@render children?.()}
</Grid>
