// packages/svelte/src/lib/components/visibility-listener/VisibilityListener.svelte
<script lang="ts">
	import { checkVisibilityAction } from "@dxdns-kit/core/actions"
	import type { HTMLAttributes } from "svelte/elements"
	import type { VisibilityListenerType } from "@dxdns-kit/core/types"

	interface Props
		extends HTMLAttributes<HTMLDivElement>,
			VisibilityListenerType {}

	let { class: className = "", callback, children, ...rest }: Props = $props()
</script>

<div
	{...rest}
	class={className}
	use:checkVisibilityAction={{
		callback
	}}
>
	{@render children?.()}
</div>

// packages/react/src/lib/components/visibility-listener/VisibilityListener.tsx
import { forwardRef, HTMLAttributes } from "react"
import { useAction } from "@/utils"
import { checkVisibilityAction } from "@dxdns-kit/core/actions"
import type { VisibilityListenerType } from "@dxdns-kit/core/types"

interface Props
	extends HTMLAttributes<HTMLDivElement>,
		VisibilityListenerType {}

export default forwardRef<HTMLDivElement, Props>(
	({ className = "", callback, children, ...rest }, _ref) => {
		const actionRef = useAction<
			HTMLDivElement,
			Parameters<typeof checkVisibilityAction>[1]
		>(checkVisibilityAction, { callback })

		return (
			<div {...rest} ref={actionRef} className={className}>
				{children}
			</div>
		)
	}
)
