// packages/react/src/lib/components/accordion/Accordion.tsx
import { forwardRef, HTMLAttributes, type PropsWithChildren } from "react"
import type { AccordionType } from "@feflow/core/types"
import { classMapUtil } from "@feflow/core/utils"
import styles from "@feflow/core/styles/Accordion.module.css"

interface Props
	extends Omit<HTMLAttributes<HTMLDivElement>, "id">,
		PropsWithChildren,
		AccordionType {}

export default forwardRef<HTMLDivElement, Props>(
	({ className, label, variant, children, ...rest }, ref) => {
		return (
			<div
				ref={ref}
				className={classMapUtil(
					className,
					[className, styles],
					[variant, styles],
					styles.accordion
				)}
				style={rest.style}
			>
				<input
					{...rest}
					className={styles.controller}
					type="radio"
					id={rest.id}
					name="accordion"
					hidden
					style={undefined}
				/>
				<label htmlFor={rest.id} className={styles.header}>
					<label htmlFor={rest.id}>{label}</label>
					<div className={styles.icon}>
						<span>icon</span>
					</div>
				</label>
				<div className={styles.content}>{children}</div>
			</div>
		)
	}
)

// src/lib/components/accordion/Accordion.svelte
<script lang="ts">
	import type { ClassValue, HTMLAttributes } from "svelte/elements"
	import type { VariantType } from "../../types/index.js"
	import classMapUtil from "../../utils/classMapUtil.js"
	import styles from "./Accordion.module.css"
	import Button from "../button/index.js"

	interface Props extends HTMLAttributes<HTMLDivElement> {
		class?: ClassValue
		open: boolean
		label: string
		variant?: VariantType
	}

	let {
		class: className = "",
		open,
		label,
		variant = "contained",
		children,
		...rest
	}: Props = $props()
</script>

<div class={styles.accordion} {...rest}>
	<Button
		class={classMapUtil({
			[styles.active]: open,
			[styles[variant]]: true
		})}
	>
		{label}
	</Button>
	<div
		class={classMapUtil({
			[styles.content]: true,
			[styles.active]: open
		})}
	>
		{@render children?.()}
	</div>
</div>
