// packages/svelte/src/lib/components/grid/Grid.svelte
<script lang="ts">
	import type { HTMLAttributes } from "svelte/elements"
	import {
		classMapUtil,
		mergeStyleUtil,
		normalizeSizeUtil
	} from "@dxdns-kit/core/utils"
	import type { GridType } from "@dxdns-kit/core/types"
	import styles from "@dxdns-kit/core/styles/Grid.module.css"

	interface Props extends HTMLAttributes<HTMLDivElement>, GridType {}

	let {
		class: className = "",
		variant,
		columns = "auto-fit",
		gap = "0.75rem",
		minWidth = "12.5rem",
		maxWidth = "1fr",
		children,
		...rest
	}: Props = $props()
</script>

<div
	{...rest}
	class={classMapUtil(
		className,
		[className, styles],
		[variant, styles],
		styles.grid
	)}
	style={mergeStyleUtil(
		`--columns: ${columns}; 
		--gap: ${normalizeSizeUtil(gap)};
		--min-width: ${normalizeSizeUtil(minWidth)};
		--max-width: ${normalizeSizeUtil(maxWidth)};`,
		rest.style
	)}
>
	{@render children?.()}
</div>

// packages/react/src/lib/components/grid/Grid.tsx
import { CSSProperties, forwardRef, HTMLAttributes } from "react"
import { classMapUtil, normalizeSizeUtil } from "@dxdns-kit/core/utils"
import type { GridType } from "@dxdns-kit/core/types"
import styles from "@dxdns-kit/core/styles/Grid.module.css"

interface Props extends HTMLAttributes<HTMLDivElement>, GridType {}

export default forwardRef<HTMLDivElement, Props>(
	(
		{
			className = "",
			variant,
			columns = "auto-fit",
			gap = "0.75rem",
			minWidth = "12.5rem",
			maxWidth = "1fr",
			children,
			...rest
		},
		ref
	) => {
		return (
			<div
				{...rest}
				ref={ref}
				className={classMapUtil(
					className,
					[className, styles],
					[variant, styles],
					styles.grid
				)}
				style={
					{
						["--columns"]: columns,
						["--gap"]: normalizeSizeUtil(gap),
						["--min-width"]: normalizeSizeUtil(minWidth),
						["--max-width"]: normalizeSizeUtil(maxWidth),
						...rest.style
					} as CSSProperties
				}
			>
				{children}
			</div>
		)
	}
)
