// packages/react/src/lib/components/accordion/Accordion.tsx
import { forwardRef, HTMLAttributes } from "react"
import type { AccordionType } from "@feflow-ui/core/types"
import { classMapUtil } from "@feflow-ui/core/utils"
import { keyboardArrowLeftIcon } from "@feflow-ui/core/icons"
import styles from "@feflow-ui/core/styles/Accordion.module.css"

interface Props
	extends Omit<HTMLAttributes<HTMLDivElement>, "id">,
		AccordionType {}

export default forwardRef<HTMLDivElement, Props>(
	({ className = "", label, variant, children, ...rest }, ref) => {
		return (
			<div
				ref={ref}
				className={classMapUtil(
					className,
					[className, styles],
					[variant, styles],
					styles.accordion
				)}
				style={rest.style}
			>
				<input
					{...rest}
					className={styles.controller}
					type="radio"
					id={rest.id}
					name="accordion"
					hidden
					style={undefined}
				/>
				<label htmlFor={rest.id} className={styles.header}>
					<label htmlFor={rest.id}>{label}</label>
					<div className={styles.icon}>
						<svg
							viewBox="0 -960 960 960"
							style={{
								display: "inline-block",
								verticalAlign: "middle",
								fill: "currentcolor",
								width: "24px",
								height: "24px"
							}}
						>
							<path d={keyboardArrowLeftIcon}></path>
						</svg>
					</div>
				</label>
				<div className={styles.content}>{children}</div>
			</div>
		)
	}
)

// packages/svelte/src/lib/components/accordion/Accordion.svelte
<script lang="ts">
	import type { HTMLInputAttributes } from "svelte/elements"
	import type { AccordionType } from "@feflow-ui/core/types"
	import { classMapUtil } from "@feflow-ui/core/utils"
	import { keyboardArrowLeftIcon } from "@feflow-ui/core/icons"
	import styles from "@feflow-ui/core/styles/Accordion.module.css"

	interface Props extends Omit<HTMLInputAttributes, "id">, AccordionType {}

	let {
		class: className = "",
		label,
		variant,
		children,
		...rest
	}: Props = $props()
</script>

<div
	class={classMapUtil(
		className,
		[className, styles],
		[variant, styles],
		styles.accordion
	)}
	style={rest.style}
>
	<input
		{...rest}
		class={styles.controller}
		type="radio"
		id={rest.id}
		name="accordion"
		hidden
		style={undefined}
	/>
	<label for={rest.id} class={styles.header}>
		<label for={rest.id}>{label}</label>
		<div class={styles.icon}>
			<svg
				viewBox="0 -960 960 960"
				style="
				display: inline-block; 
				vertical-align: middle;
				fill: currentColor;
				width: 24px;
				height: 24px;
				"
			>
				<path d={keyboardArrowLeftIcon}></path>
			</svg>
		</div>
	</label>
	<div class={styles.content}>
		{@render children?.()}
	</div>
</div>
