// packages/feflow/src/lib/components/toast/Toaster.svelte
<script lang="ts">
	import type { PositionType } from "../../types/index.js"
	import { toastState } from "../../states/index.js"
	import Toast from "./Toast.svelte"
	import { fade } from "svelte/transition"
	import type { HTMLAttributes } from "svelte/elements"
	import { classMapUtil, mergeStyleUtil } from "@dxdns/feflow-core/utils"
	import styles from "./Toaster.module.css"
	import { flip } from "svelte/animate"

	interface Props extends HTMLAttributes<HTMLDivElement> {
		fullWidth?: boolean
	}

	let { class: className, fullWidth, ...rest }: Props = $props()

	let isHovered = $state(false)

	const toast = toastState()
	const maxToasts = fullWidth ? 1 : 3
	const positions = [
		"top-left",
		"top-right",
		"bottom-left",
		"bottom-right",
		"top-center",
		"bottom-center"
	] as const satisfies PositionType[]
</script>

{#each positions as position}
	{@const pos = position.split("-")[0]}
	{@const isPositionTop = pos === "top"}
	{@const grouped = toast
		.getAll()
		.filter((t) => t.position === position)
		.slice(-maxToasts)
		.reverse()}
	<div
		{...rest}
		class={classMapUtil(
			className,
			[styles, className],
			styles.toaster,
			[position, styles],
			[pos, styles],
			{
				[styles.fullWidth]: fullWidth
			}
		)}
	>
		{#each grouped as item, i (item.id)}
			<div
				role="region"
				class={styles.wrapper}
				animate:flip
				transition:fade={{ duration: 150 }}
				onmouseenter={() => {
					isHovered = true
					toast.pauseAll()
				}}
				onmouseleave={() => {
					isHovered = false
					toast.resumeAll()
				}}
				style={mergeStyleUtil(
					`
						--toast-padding: 0.75rem 0;
						--toast-side-offset: 0.5rem;
						--toast-opacity: ${isHovered ? 1 : 1 - i * 0.08};
						--toast-z-index: ${isHovered ? 1000 : 1000 - i};
						--toast-translate: ${isPositionTop ? i * (isHovered ? 48 : 8) : -i * (isHovered ? 48 : 8)}px;
						--toast-scale: ${isHovered ? 1 : 1 - i * 0.05};
					`,
					rest.style
				)}
			>
				<Toast
					{...item}
					class={styles.toast}
					handleClose={() => {
						toast.remove(item.id)
					}}
				/>
			</div>
		{/each}
	</div>
{/each}

// packages/react/src/lib/components/toast/Toaster.tsx
import { CSSProperties, useState, type PropsWithChildren } from "react"
import type { AlignmentType, ToasterType } from "@dxdns-kit/core/types"
import { ToastContext } from "../../contexts/ToastContext"
import { Constants } from "@dxdns-kit/core"
import { classMapUtil } from "@dxdns-kit/core/utils"
import Toast from "./Toast"
import styles from "@dxdns-kit/core/styles/Toaster.module.css"

type Props = PropsWithChildren & {
	fullWidth?: boolean
}

export default function ({ fullWidth = false, children }: Props) {
	const [isHovered, setIsHovered] = useState(false)
	const [data, setData] = useState<Map<string, ToasterType>>(new Map())

	const maxToasts = Constants.MAX_TOASTS(fullWidth)

	function remove(id: string) {
		setData((prev) => {
			const newMap = new Map(prev)
			newMap.delete(id)
			return newMap
		})
	}

	function add(toast: ToasterType) {
		const id = crypto.randomUUID()
		const duration = toast.duration ?? Constants.TOAST_DEFAULT_DURATION
		const position = toast.position ?? "bottom-right"

		setData((old) => {
			const newMap = new Map(old)
			newMap.set(id, { ...toast, duration, position })
			return newMap
		})

		return id
	}

	function groupedData(alignment: AlignmentType) {
		return Array.from(data)
			.filter(([_, t]) => t.position === alignment)
			.slice(-maxToasts)
			.reverse()
	}

	return (
		<ToastContext.Provider value={{ data: data, add, remove }}>
			{Constants.alignments.map((alignment) => {
				const pos = alignment.split("-")[0]
				const isPositionTop = pos === "top"
				const grouped = groupedData(alignment)

				return (
					<div
						key={alignment}
						className={classMapUtil(
							[alignment, styles],
							[pos, styles],
							{
								[styles.fullWidth]: fullWidth
							},
							styles.toaster
						)}
					>
						{Array.from(grouped).map(([id, item], i) => (
							<div
								key={id}
								role="region"
								className={styles.wrapper}
								onMouseEnter={() => {
									setIsHovered(true)
								}}
								onMouseLeave={() => {
									setIsHovered(false)
								}}
								style={
									{
										["--toast-opacity"]: isHovered ? 1 : 1 - i * 0.08,
										["--toast-z-index"]: isHovered ? 1000 : 1000 - i,
										["--toast-translate"]: `${isPositionTop ? i * (isHovered ? 52 : 8) : -i * (isHovered ? 52 : 8)}px`,
										["--toast-scale"]: isHovered ? 1 : 1 - i * 0.05
									} as CSSProperties
								}
							>
								<Toast {...item} id={id} className={styles.toast} />
							</div>
						))}
					</div>
				)
			})}
			{children}
		</ToastContext.Provider>
	)
}
