// packages/docs/src/lib/components/BottomSheetPreview.tsx
import { BottomSheet, Button } from "@dxdns/feflow-react"
import { useState } from "react"

export default function () {
	const [isOpen, setIsOpen] = useState(false)

	function handleOpen() {
		setIsOpen((old) => !old)
	}

	function handleClose() {
		setIsOpen(false)
	}

	return (
		<>
			<BottomSheet.Overlay
				isOpen={isOpen}
				onClick={handleClose}
				style={{ zIndex: 998 }}
			/>
			<BottomSheet isOpen={isOpen} handleClose={handleClose}>
				<h1>test</h1>
			</BottomSheet>

			<Button onClick={handleOpen}>Open</Button>
		</>
	)
}

// packages/docs/src/lib/components/svelte/BottomSheetPreview.svelte
<script lang="ts">
	import { BottomSheet, Button } from "@dxdns/feflow-svelte"

	let isOpen = $state(false)

	function handleClose() {
		isOpen = false
	}
</script>

<BottomSheet.Overlay {isOpen} onclick={handleClose} style="z-index: 998;" />
<BottomSheet {isOpen} {handleClose}>
	<h1>test</h1>
</BottomSheet>

<Button
	onclick={() => {
		isOpen = !isOpen
	}}
>
	Open
</Button>
