// packages/docs/src/lib/components/ColorPickerPreview.tsx
import { ColorPicker } from "@dxdns/feflow-react"
import { useState, type CSSProperties } from "react"

export default function () {
	const [color, setColor] = useState("#fde6b0")
	return (

		<div style={{ display: "flex", alignItems: "center", gap: "1rem" }}>
			<ColorPicker
				value={color}
				onInput={(e) => {
					const input = e.currentTarget as HTMLInputElement
					setColor(input.value)
				}}
			/>
			<div style={{
				width: "38px",
				height: "38px",
				border: "1px solid var(--ff-border)",
				borderRadius: "0.25rem",
				background: "var(--color)",
				["--color"]: color,
			} as CSSProperties}></div>
			<span style={{ color }}>{color}</span>
		</div>
	)
}

// packages/docs/src/lib/components/svelte/ColorPickerPreview.svelte
<script lang="ts">
	import { ColorPicker } from "@dxdns/feflow-svelte"

	let color = $state("#fde6b0")
</script>

<div style="display:flex; align-items:center; gap:1rem;">
	<ColorPicker
		value={color}
		oninput={(e) => {
			const input = e.currentTarget as HTMLInputElement
			color = input.value
		}}
	/>
	<div class="colorPreview" style="--color: {color}"></div>
	<span style="color: {color};">{color}</span>
</div>

<style>
	.colorPreview {
		width: 38px;
		height: 38px;
		border: 1px solid var(--ff-border);
		border-radius: 0.25rem;
		background: var(--color);
	}
</style>
