// packages/docs/src/lib/components/ToastPreview.tsx
import { Constants } from "@fefade/core"
import { Button, Toaster, useToast } from "@fefade/react"

function ToastPreview() {
	const toast = useToast()

	const positions = [
		"top-left",
		"bottom-left",
		"top-right",
		"bottom-right",
		"bottom-center",
		"top-center"
	] as const

	return (
		<div
			style={{
				display: "flex",
				gap: "1rem",
				alignItems: "center",
				flexWrap: "wrap"
			}}
		>
			{Constants.statusColors.map((color) => (
				<Button
					key={color}
					onClick={() => {
						toast.add({
							message: color,
							color
						})
					}}
					className={`bg-${color} text-on-${color}`}
				>
					{color}
				</Button>
			))}

			{positions.map((position) => (
				<Button
					key={position}
					onClick={() => {
						toast.add({
							message: position,
							position
						})
					}}
				>
					{position}
				</Button>
			))}

			<Button
				onClick={() => {
					toast.add({
						message: "Duration: 50000",
						duration: 50000
					})
				}}
			>
				Duration: 50000
			</Button>

			<Button
				onClick={() => {
					toast.add({
						message: "closable",
						isClosable: true
					})
				}}
			>
				Closable
			</Button>

			<Button
				onClick={() => {
					toast.add({
						message: "with progress loader",
						withProgressLoader: true,
						duration: 15000
					})
				}}
			>
				With Progress Loader
			</Button>
		</div>
	)
}

export default function () {
	return (
		<Toaster>
			<ToastPreview />
		</Toaster>
	)
}

// packages/docs/src/lib/components/svelte/ToastPreview.svelte
<script lang="ts">
	import { Button, toast, Toaster } from "@feflow/svelte"

	const colors = ["error", "success", "warning"]
	const positions = [
		"top-left",
		"bottom-left",
		"top-right",
		"bottom-right",
		"bottom-center",
		"top-center"
	]
</script>

<Toaster />

<div style="display: flex; gap: 1rem; align-items: center; flex-wrap: wrap;">
	{#each colors as color}
		<Button
			onclick={() => {
				toast({ message: color, color: color as any })
			}}
		>
			{color}
		</Button>
	{/each}

	{#each positions as position}
		<Button
			onclick={() => {
				toast({ message: position, position: position as any })
			}}
		>
			{position}
		</Button>
	{/each}

	<Button
		onclick={() => {
			toast({ message: "Duration: 15000", duration: 15000 })
		}}
	>
		Duration: 15000
	</Button>

	<Button
		onclick={() => {
			toast({ message: "closable", isClosable: true })
		}}
	>
		Closable
	</Button>
</div>
