// src/lib/components/avatar/Avatar.svelte
<script lang="ts">
  import type { ClassValue, HTMLImgAttributes } from "svelte/elements"
  import classMapUtil from "../../utils/classMapUtil.js"
  import styles from "./Avatar.module.css"

  interface Props extends HTMLImgAttributes {
    class?: ClassValue
    textFallback?: string
  }

  let { class: className = "", textFallback, ...rest }: Props = $props()

  let hasError = $state(false)

  function handleError() {
    hasError = true
  }
</script>

<div
  class={classMapUtil({
    [styles.avatar]: true,
  })}
>
  {#if !hasError}
    <img
      class={classMapUtil({
        [className as string]: true,
      })}
      {...rest}
      onerror={handleError}
    />
  {:else if textFallback}
    <span class={styles.textFallback}>
      {textFallback.charAt(0).toUpperCase()}
    </span>
  {/if}
</div>

// packages/react/src/lib/components/avatar/Avatar.tsx
import {
	forwardRef,
	useState,
	type ImgHTMLAttributes,
	type PropsWithChildren
} from "react"
import styles from "@feflow/core/styles/Avatar.module.css"
import { classMapUtil } from "@feflow/core/utils"

type Props = Omit<ImgHTMLAttributes<HTMLImageElement>, "width" | "height"> &
	PropsWithChildren & {
		textFallback?: string
		width?: string
		height?: string
	}

export default forwardRef<HTMLDivElement, Props>(
	({ className, width, height, textFallback, ...rest }, ref) => {
		const [hasError, setHasError] = useState(false)

		function handleError() {
			setHasError(true)
		}

		return (
			<div
				ref={ref}
				className={classMapUtil(className, [className, styles], styles.avatar)}
				style={{ width, height }}
			>
				{!hasError && rest.src ? (
					<img onError={handleError} {...rest} />
				) : (
					textFallback && (
						<span className={styles.textFallback}>
							{textFallback.charAt(0).toUpperCase()}
						</span>
					)
				)}
			</div>
		)
	}
)
