// packages/feflow/src/lib/components/avatar/Avatar.svelte
<script lang="ts">
	import type { HTMLImgAttributes } from "svelte/elements"
	import { classMapUtil } from "@dxdns/feflow-core/utils"
	import styles from "./Avatar.module.css"

	interface Props extends Omit<HTMLImgAttributes, "width" | "height"> {
		textFallback?: string
		width?: string
		height?: string
	}

	let {
		class: className = "",
		width,
		height,
		textFallback,
		...rest
	}: Props = $props()

	let hasError = $state(false)

	function handleError() {
		hasError = true
	}
</script>

<div
	class={classMapUtil(className, [className, styles], styles.avatar)}
	style="width: {width}; height: {height};"
>
	{#if !hasError && rest.src}
		<img onerror={handleError} {...rest} />
	{:else if textFallback}
		<span class={styles.textFallback}>
			{textFallback.charAt(0).toUpperCase()}
		</span>
	{/if}
</div>

// packages/react/src/lib/components/avatar/Avatar.tsx
import { forwardRef, useState, type ImgHTMLAttributes } from "react"
import styles from "@dxdns/feflow-core/styles/Avatar.module.css"
import { classMapUtil } from "@dxdns/feflow-core/utils"
import type { AvatarType } from "@dxdns/feflow-core/types"

interface Props
	extends Omit<ImgHTMLAttributes<HTMLImageElement>, "width" | "height">,
		AvatarType {}

export default forwardRef<HTMLDivElement, Props>(
	({ className, width, height, textFallback, ...rest }, ref) => {
		const [hasError, setHasError] = useState(false)

		function handleError() {
			setHasError(true)
		}

		return (
			<div
				ref={ref}
				className={classMapUtil(className, [className, styles], styles.avatar)}
				style={{ width, height }}
			>
				{!hasError && rest.src ? (
					<img {...rest} onError={handleError} />
				) : (
					textFallback && (
						<span className={styles.textFallback}>
							{textFallback.charAt(0).toUpperCase()}
						</span>
					)
				)}
			</div>
		)
	}
)
