// packages/react/src/lib/components/textarea/Textarea.tsx
import { forwardRef, HTMLAttributes } from "react"
import { classMapUtil } from "@dxdns-kit/core/utils"
import styles from "@dxdns-kit/core/styles/Textarea.module.css"

interface Props extends HTMLAttributes<HTMLTextAreaElement> {}

export default forwardRef<HTMLTextAreaElement, Props>((props, ref) => {
	const { className = "", children, ...rest } = props

	return (
		<textarea
			{...rest}
			ref={ref}
			className={classMapUtil(className, styles.textarea)}
		>
			{children}
		</textarea>
	)
})

// packages/svelte/src/lib/components/textarea/Textarea.svelte
<script lang="ts">
	import { classMapUtil } from "@dxdns-kit/core/utils"
	import type { HTMLTextareaAttributes } from "svelte/elements"
	import styles from "@dxdns-kit/core/styles/Textarea.module.css"

	interface Props extends HTMLTextareaAttributes {}

	let { class: className = "", ...rest }: Props = $props()
</script>

<textarea {...rest} class={classMapUtil(className, styles.textarea)}>
</textarea>
