// packages/react/src/lib/components/bottom-sheet/BottomSheetContent.tsx
import { classMapUtil } from "@navnex-kit/core/utils"
import { forwardRef, HTMLAttributes } from "react"
import styles from "@navnex-kit/core/styles/BottomSheetContent.module.css"

interface Props extends Omit<HTMLAttributes<HTMLDivElement>, "color"> {}

export default forwardRef<HTMLDivElement, Props>(
	({ className = "", children, ...rest }, ref) => {
		return (
			<div
				{...rest}
				ref={ref}
				className={classMapUtil(
					className,
					[className, styles],
					styles.bottomSheetContent
				)}
			>
				{children}
			</div>
		)
	}
)

// packages/svelte/src/lib/components/bottom-sheet/BottomSheetContent.svelte
<script lang="ts">
	import { classMapUtil } from "@navnex-kit/core/utils"
	import type { HTMLAttributes } from "svelte/elements"
	import styles from "@navnex-kit/core/styles/BottomSheetContent.module.css"

	interface Props extends Omit<HTMLAttributes<HTMLDivElement>, "color"> {}

	let { class: className = "", children, ...rest }: Props = $props()
</script>

<div
	{...rest}
	class={classMapUtil(
		className,
		[className, styles],
		styles.bottomSheetContent
	)}
>
	{@render children?.()}
</div>
