// packages/react/src/lib/components/drawer/DrawerHeader.tsx
import { forwardRef, HTMLAttributes } from "react"
import { classMapUtil } from "@dxdns/feflow-core/utils"
import styles from "@dxdns/feflow-core/styles/DrawerHeader.module.css"
import Button from "../button"
import { CloseIcon } from "../../icons/index.js"

export interface Props extends HTMLAttributes<HTMLDivElement> {
	handleClose?: () => void
}

export default forwardRef<HTMLDivElement, Props>((props, ref) => {
	const { className = "", handleClose, children, ...rest } = props

	return (
		<div
			{...rest}
			ref={ref}
			className={classMapUtil(
				className,
				[className, styles],
				styles.drawerHeader,
				{
					[styles.isClosable]: Boolean(handleClose)
				}
			)}
		>
			{children}
			{handleClose && (
				<Button
					variant="text"
					className={styles.buttonClose}
					onClick={handleClose}
				>
					<CloseIcon />
				</Button>
			)}
		</div>
	)
})

// packages/svelte/src/lib/components/drawer/DrawerHeader.svelte
<script lang="ts">
	import type { HTMLAttributes } from "svelte/elements"
	import { classMapUtil } from "@dxdns/feflow-core/utils"
	import { CloseIcon } from "../../icons/index.js"
	import Button from "../button/index.js"
	import styles from "@dxdns/feflow-core/styles/DrawerHeader.module.css"

	interface Props extends HTMLAttributes<HTMLDivElement> {
		handleClose?: () => void
	}

	let {
		class: className = "",
		handleClose,
		children,
		...rest
	}: Props = $props()
</script>

<div
	{...rest}
	class={classMapUtil(className, [className, styles], styles.drawerHeader, {
		[styles.isClosable]: Boolean(handleClose)
	})}
>
	{@render children?.()}
	{#if handleClose}
		<Button variant="text" class={styles.buttonClose} onclick={handleClose}>
			<CloseIcon />
		</Button>
	{/if}
</div>
