// packages/react/src/lib/components/modal/ModalActions.tsx
import type { AlignType } from "@dxdns/feflow-core/types"
import { classMapUtil } from "@dxdns/feflow-core/utils"
import { CSSProperties, forwardRef, HTMLAttributes } from "react"
import styles from "@dxdns/feflow-core/styles/ModalActions.module.css"

interface Props extends Omit<HTMLAttributes<HTMLDivElement>, "color"> {
	align?: AlignType
}

export default forwardRef<HTMLDivElement, Props>(
	({ className = "", align = "end", children, ...rest }, ref) => {
		return (
			<div
				{...rest}
				ref={ref}
				className={classMapUtil(className, [className, styles], styles.actions)}
				style={
					{
						["--align"]: align,
						...rest.style
					} as CSSProperties
				}
			>
				{children}
			</div>
		)
	}
)

// packages/feflow/src/lib/components/modal/ModalActions.svelte
<script lang="ts">
	import type { HTMLAttributes } from "svelte/elements"
	import { classMapUtil, mergeStyleUtil } from "@dxdns/feflow-core/utils"
	import type { AlignType } from "../../types/index.js"

	export interface ModalActionsProps {
		align?: AlignType
	}

	interface Props extends ModalActionsProps, HTMLAttributes<HTMLDivElement> {}

	let {
		class: className = "",
		align = "end",
		children,
		...rest
	}: Props = $props()
</script>

<div
	{...rest}
	class={classMapUtil(className, "actions")}
	style={mergeStyleUtil(`--align: ${align};`, rest.style)}
>
	{@render children?.()}
</div>

<style>
	.actions {
		display: flex;
		justify-content: var(--align, flex-end);
		gap: 0.5rem;
		padding: 0.75rem 1rem;
		border-top: 1px solid var(--ff-border);
		flex-wrap: wrap;
		margin-top: 0;
	}

	.actions.border-0 {
		border-top: none;
	}
</style>
