// packages/feflow/src/lib/components/badge/Badge.svelte
<script lang="ts">
	import type { HTMLAttributes } from "svelte/elements"
	import styles from "./Badge.module.css"
	import type { SizeType, VariantType } from "../../types/index.js"
	import { classMapUtil } from "@dxdns/feflow-core/utils"

	interface Props extends HTMLAttributes<HTMLSpanElement> {
		size?: SizeType
		variant?: Exclude<VariantType, "text">
		roundedFull?: boolean
	}

	let {
		class: className = "",
		size = "xs",
		variant = "contained",
		roundedFull = false,
		children,
		...rest
	}: Props = $props()
</script>

<span
	{...rest}
	class={classMapUtil(
		className,
		[className, styles],
		styles.badge,
		[size, styles],
		[variant, styles],
		{ [styles.roundedFull]: roundedFull }
	)}
>
	{@render children?.()}
</span>

// packages/react/src/lib/components/badge/Badge.tsx
import { forwardRef, HTMLAttributes } from "react"
import { classMapUtil } from "@dxdns/feflow-core/utils"
import styles from "@dxdns/feflow-core/styles/Badge.module.css"
import type { BadgeType } from "@dxdns/feflow-core/types"

interface Props extends HTMLAttributes<HTMLSpanElement>, BadgeType {}

export default forwardRef<HTMLDivElement, Props>(
	(
		{
			className,
			size = "xs",
			variant = "contained",
			roundedFull = false,
			children,
			...rest
		},
		ref
	) => {
		return (
			<span
				{...rest}
				ref={ref}
				className={classMapUtil(
					className,
					[className, styles],
					styles.badge,
					[size, styles],
					[variant, styles],
					{
						[styles.roundedFull]: roundedFull
					}
				)}
			>
				{children}
			</span>
		)
	}
)
